# -*- coding: UTF-8 -*-

# 아이폰용 Blendshape 이름들
ARKitBlendShapeList = [u'eyeBlinkLeft', u'eyeLookDownLeft', u'eyeLookInLeft', u'eyeLookOutLeft', u'eyeLookUpLeft', u'eyeSquintLeft', u'eyeWideLeft', u'eyeBlinkRight', u'eyeLookDownRight', u'eyeLookInRight', u'eyeLookOutRight', u'eyeLookUpRight', u'eyeSquintRight', u'eyeWideRight', u'jawForward', u'jawLeft', u'jawRight', u'jawOpen', u'mouthClose', u'mouthFunnel', u'mouthPucker', u'mouthRight', u'mouthLeft', u'mouthSmileLeft', u'mouthSmileRight', u'mouthFrownRight', u'mouthFrownLeft', u'mouthDimpleLeft', u'mouthDimpleRight', u'mouthStretchLeft', u'mouthStretchRight', u'mouthRollLower', u'mouthRollUpper', u'mouthShrugLower', u'mouthShrugUpper', u'mouthPressLeft', u'mouthPressRight', u'mouthLowerDownLeft', u'mouthLowerDownRight', u'mouthUpperUpLeft', u'mouthUpperUpRight', u'browDownLeft', u'browDownRight', u'browInnerUp', u'browOuterUpLeft', u'browOuterUpRight', u'cheekPuff', u'cheekSquintLeft', u'cheekSquintRight', u'noseSneerLeft', u'noseSneerRight', u'tongueOut']
ICTBlendShapeList = [u'eyeBlinkLeft', u'eyeBlinkRight', u'eyeLookDownLeft', u'eyeLookDownRight', u'eyeLookInLeft', u'eyeLookInRight', u'eyeLookOutLeft', u'eyeLookOutRight', u'eyeLookUpLeft', u'eyeLookUpRight', u'eyeSquintLeft', u'eyeSquintRight', u'eyeWideLeft', u'eyeWideRight', u'browDownLeft', u'browDownRight', u'browInnerUp', u'browInnerUpLeft', u'browInnerUpRight', u'browOuterUpLeft', u'browOuterUpRight', u'jawOpen', u'jawRight', u'jawForward', u'jawLeft', u'mouthClose', u'mouthDimpleLeft', u'mouthDimpleRight', u'mouthFrownLeft', u'mouthFrownRight', u'mouthFunnel', u'mouthLeft', u'mouthLowerDownLeft', u'mouthLowerDownRight', u'mouthPressLeft', u'mouthPressRight', u'mouthPucker', u'mouthRight', u'mouthRollLower', u'mouthRollUpper', u'mouthShrugLower', u'mouthShrugUpper', u'mouthSmileLeft', u'mouthSmileRight', u'mouthStretchLeft', u'mouthStretchRight', u'mouthUpperUpLeft', u'mouthUpperUpRight', u'cheekPuff', u'cheekPuffLeft', u'cheekPuffRight', u'cheekRaiserLeft', u'cheekRaiserRight', u'cheekSquintLeft', u'cheekSquintRight', u'noseSneerLeft', u'noseSneerRight', u'tongueOut']


# Control rig 선택
JBControlRigList = [u'L_squeeze_Ctrl', u'R_Nose_Ctrl_Angry', u'L_Nose_Ctrl_Angry', u'Lip_ctrl_M_UP', u'R_squeeze_Ctrl', u'R_Close_eye_Down', u'R_Close_eye_up', u'L_Close_eye_Down', u'L_Close_eye_up', u'M_Brow_Ctrl', u'M_Jaw_Ctrl', u'M_Tongue_Ctrl', u'M_Cheek_Ctrl', u'Lip_ctrl_R_Down', u'Lip_ctrl_R_UP', u'M_Roll_Ctrl', u'Lip_ctrl_R_End', u'Lip_ctrl_L_UP', u'Lip_ctrl_M_Down', u'Lip_ctrl_L_End', u'Lip_ctrl_L_Down', u'Look_Ctrl', u'L_brow_up_Ctrl', u'R_brow_up_Ctrl', u'brow_ctrl_Mid']
JBControlRigList_v2 = [u'mouth_press_R_ctl', u'mouth_press_L_ctl', u'cheekRaiser_R_ctl', u'eyelid_Up_L_ctl', u'eyeSquint_R_ctl', u'eyeSquint_L_ctl', u'mouthPucker_ctl', u'mouthDimple_L_ctl', u'cheekRaiser_L_ctl', u'cheekSquint_L_ctl', u'cheekSquint_R_ctl', u'browOuterUp_L_ctl', u'browOuterUp_R_ctl', u'browInnerUp_L_ctl', u'browInnerUp_R_ctl', u'eyelid_Up_R_ctl', u'eye_control', u'mouthClose_ctl', u'mouth_end_R_ctrl', u'mouth_end_L_ctrl', u'mouthLowerDown_R_ctl', u'cheekPuff_R_ctl', u'cheekPuff_L_ctl', u'noseSneer_R_ctl', u'noseSneer_L_ctl', u'jaw_ctl', u'mouthDimple_R_ctl', u'mouth_L_R_ctl', u'mouthLowerDown_L_ctl', u'mouthShrugLower_ctl', u'mouthShrugUpper_ctl', u'mouthUpperUp_R_ctl', u'mouthUpperUp_L_ctl', u'mouthRollUpper_ctl', u'mouthFunnel_ctl', u'mouthRollLower_ctl', u'Jaw_F_ctl']

# Control rig와 Blendshape 연결 정보
JBControlConnectionInfo = [[u'BS_node.eyeBlinkLeft', u'BS_node_eyeBlinkLeft'], [u'BS_node.eyeLookDownLeft', u'BS_node_eyeLookDownLeft'], [u'BS_node.eyeLookInLeft', u'BS_node_eyeLookInLeft'], [u'BS_node.eyeLookOutLeft', u'BS_node_eyeLookOutLeft'], [u'BS_node.eyeLookUpLeft', u'BS_node_eyeLookUpLeft'], [u'BS_node.eyeSquintLeft', u'BS_node_eyeSquintLeft'], [u'BS_node.eyeWideLeft', u'BS_node_eyeWideLeft'], [u'BS_node.eyeBlinkRight', u'BS_node_eyeBlinkRight'], [u'BS_node.eyeLookDownRight', u'BS_node_eyeLookDownRight'], [u'BS_node.eyeLookInRight', u'BS_node_eyeLookInRight'], [u'BS_node.eyeLookOutRight', u'BS_node_eyeLookOutRight'], [u'BS_node.eyeLookUpRight', u'BS_node_eyeLookUpRight'], [u'BS_node.eyeSquintRight', u'BS_node_eyeSquintRight'], [u'BS_node.eyeWideRight', u'BS_node_eyeWideRight'], [u'BS_node.jawForward', u'BS_node_jawForward'], [u'BS_node.jawLeft', u'BS_node_jawLeft'], [u'BS_node.jawRight', u'BS_node_jawRight'], [u'BS_node.jawOpen', u'BS_node_jawOpen'], [u'BS_node.mouthClose', u'BS_node_mouthClose'], [u'BS_node.mouthFunnel', u'blendWeighted2'], [u'BS_node.mouthPucker', u'blendWeighted3'], [u'BS_node.mouthRight', u'BS_node_mouthRight'], [u'BS_node.mouthLeft', u'BS_node_mouthLeft'], [u'BS_node.mouthSmileLeft', u'BS_node_mouthSmileLeft'], [u'BS_node.mouthSmileRight', u'BS_node_mouthSmileRight'], [u'BS_node.mouthFrownRight', u'BS_node_mouthFrownRight'], [u'BS_node.mouthFrownLeft', u'BS_node_mouthFrownLeft'], [u'BS_node.mouthDimpleLeft', u'BS_node_mouthDimpleLeft'], [u'BS_node.mouthDimpleRight', u'BS_node_mouthDimpleRight'], [u'BS_node.mouthStretchLeft', u'BS_node_mouthStretchLeft'], [u'BS_node.mouthStretchRight', u'BS_node_mouthStretchRight'], [u'BS_node.mouthRollLower', u'BS_node_mouthRollLower'], [u'BS_node.mouthRollUpper', u'BS_node_mouthRollUpper'], [u'BS_node.mouthShrugLower', u'blendWeighted4'], [u'BS_node.mouthShrugUpper', u'BS_node_mouthShrugUpper'], [u'BS_node.mouthLowerDownLeft', u'BS_node_mouthLowerDownLeft'], [u'BS_node.mouthLowerDownRight', u'BS_node_mouthLowerDownRight'], [u'BS_node.mouthUpperUpLeft', u'BS_node_mouthUpperUpLeft'], [u'BS_node.mouthUpperUpRight', u'BS_node_mouthUpperUpRight'], [u'BS_node.browDownLeft', u'BS_node_browDownLeft1'], [u'BS_node.browDownRight', u'BS_node_browDownRight'], [u'BS_node.browInnerUp', u'BS_node_browInnerUp'], [u'BS_node.browOuterUpLeft', u'BS_node_browOuterUpLeft1'], [u'BS_node.browOuterUpRight', u'BS_node_browOuterUpRight'], [u'BS_node.cheekPuff', u'BS_node_cheekPuff'], [u'BS_node.cheekSquintLeft', u'BS_node_cheekSquintLeft'], [u'BS_node.cheekSquintRight', u'blendWeighted1'], [u'BS_node.noseSneerLeft', u'BS_node_noseSneerLeft'], [u'BS_node.noseSneerRight', u'BS_node_noseSneerRight'], [u'BS_node.tongueOut', u'BS_node_tongueOut']]
# Control rig와 Blendshape 연결 정보 ICT 최신 컨트롤 리그 2020년 12월9일 추가
JBC_BSList = [u'BS_node.mouthFrownLeft', u'BS_node.mouthDimpleRight', u'BS_node.mouthDimpleLeft', u'BS_node.mouthClose', u'BS_node.jawRight', u'BS_node.jawOpen', u'BS_node.jawLeft', u'BS_node.jawForward', u'BS_node.mouthFunnel', u'BS_node.mouthFrownRight', u'BS_node.eyeWideRight', u'BS_node.cheekRaiserLeft', u'BS_node.cheekPuffRight', u'BS_node.cheekPuffLeft', u'BS_node.browOuterUpRight', u'BS_node.browOuterUpLeft', u'BS_node.browInnerUpRight', u'BS_node.browInnerUpLeft', u'BS_node.browDownRight', u'BS_node.browDownLeft', u'BS_node.noseSneerRight', u'BS_node.noseSneerLeft', u'BS_node.mouthUpperUpRight', u'BS_node.mouthUpperUpLeft', u'BS_node.mouthStretchRight', u'BS_node.mouthStretchLeft', u'BS_node.eyeLookInLeft', u'BS_node.eyeLookDownRight', u'BS_node.eyeLookDownLeft', u'BS_node.eyeBlinkRight', u'BS_node.eyeBlinkLeft', u'BS_node.cheekSquintRight', u'BS_node.cheekSquintLeft', u'BS_node.cheekRaiserRight', u'BS_node.eyeWideLeft', u'BS_node.eyeSquintRight', u'BS_node.eyeSquintLeft', u'BS_node.eyeLookUpRight', u'BS_node.eyeLookUpLeft', u'BS_node.eyeLookOutRight', u'BS_node.eyeLookOutLeft', u'BS_node.eyeLookInRight', u'BS_node.mouthPucker', u'BS_node.mouthLowerDownRight', u'BS_node.mouthPressRight', u'BS_node.mouthPressLeft', u'BS_node.mouthRollLower', u'BS_node.mouthRight', u'BS_node.mouthRollUpper', u'BS_node.mouthSmileLeft', u'BS_node.mouthShrugUpper', u'BS_node.mouthShrugLower', u'BS_node.mouthSmileRight', u'BS_node.mouthLowerDownLeft', u'BS_node.mouthLeft']
JBC_CtrlList = [u'blendShape1_mouthFrown_L_Mesh.output', u'mouthDimple_R_ctl.translateY', u'mouthDimple_L_ctl.translateY', u'mouthClose_ctl.translateY', u'blendShape1_jawRight_Mesh.output', u'jaw_ctl.translateY', u'blendShape1_jawLeft_Mesh.output', u'Jaw_F_ctl.translateY', u'mouthFunnel_ctl.translateY', u'blendShape1_mouthFrown_R_Mesh1.output', u'blendShape1_eyeWide_R_Mesh.output', u'cheekRaiser_L_ctl.translateY', u'cheekPuff_R_ctl.translateY', u'cheekPuff_L_ctl.translateY', u'blendShape1_browOuterUp_R_Mesh.output', u'blendShape1_browOuterUp_L_Mesh.output', u'browInnerUp_R_ctl.translateY', u'browInnerUp_L_ctl.translateY', u'blendShape1_browDown_R_Mesh.output', u'blendShape1_browDown_L_Mesh.output', u'noseSneer_R_ctl.translateY', u'noseSneer_L_ctl.translateY', u'mouthUpperUp_R_ctl.translateY', u'mouthUpperUp_L_ctl.translateY', u'mouth_end_R_ctrl.translateY', u'mouth_end_L_ctrl.translateY', u'blendShape1_eyeLookIn_L_Mesh.output', u'blendShape1_eyeLookDown_R_Mesh.output', u'blendShape1_eyeLookDown_L_Mesh.output', u'blendShape1_eyeBlink_R_Mesh.output', u'blendShape1_eyeBlink_L_Mesh.output', u'cheekSquint_R_ctl.translateY', u'cheekSquint_L_ctl.translateY', u'cheekRaiser_R_ctl.translateY', u'blendShape1_eyeWide_L_Mesh.output', u'eyeSquint_R_ctl.translateY', u'eyeSquint_L_ctl.translateY', u'blendShape1_eyeLookUp_R_Mesh.output', u'blendShape1_eyeLookUp_L_Mesh.output', u'blendShape1_eyeLookOut_R_Mesh.output', u'blendShape1_eyeLookOut_L_Mesh.output', u'blendShape1_eyeLookIn_R_Mesh.output', u'mouthPucker_ctl.translateY', u'mouthLowerDown_R_ctl.translateY', u'mouth_press_R_ctl.translateY', u'mouth_press_L_ctl.translateY', u'mouthRollLower_ctl.translateY', u'blendShape1_mouthRight_Mesh.output', u'mouthRollUpper_ctl.translateY', u'blendShape1_mouthSmile_L_Mesh.output', u'mouthShrugUpper_ctl.translateY', u'mouthShrugLower_ctl.translateY', u'blendShape1_mouthSmile_R_Mesh1.output', u'mouthLowerDown_L_ctl.translateY', u'blendShape1_mouthLeft_Mesh.output']
'''
# 연결정보 추출하기
def getBlendshapeConnects():
    bsName = 'BS_node'
    BSList = []
    CtrlList = []
    blendshapes = cmds.listAttr( bsName + '.w', m=True)
    for bs in blendshapes:
        BSList.append(bsName+ '.' + bs)
        connect = cmds.listConnections(bsName + '.' + bs, d=False, s=True)
        if connect:
            CtrlList.append(connect[0])
    print BSList
    print CtrlList
getBlendshapeConnects()

# 다시 연결하기
for bs, ctrl in zip(BSList, CtrlList):
    #cmds.connectAttr(bs + '.output',ctrl)
    print bs, ctrl

'''


# 숨겨져 있는 오브젝트(익스포트시 사용)
JBChiddenControlRig = [u'BS_node_eyeBlinkLeft', u'BS_node_eyeLookDownLeft', u'BS_node_eyeLookInLeft', u'BS_node_eyeLookOutLeft', u'BS_node_eyeLookUpLeft', u'BS_node_eyeSquintLeft', u'BS_node_eyeWideLeft', u'BS_node_eyeBlinkRight', u'BS_node_eyeLookDownRight', u'BS_node_eyeLookInRight', u'BS_node_eyeLookOutRight', u'BS_node_eyeLookUpRight', u'BS_node_eyeSquintRight', u'BS_node_eyeWideRight', u'BS_node_jawForward', u'BS_node_jawLeft', u'BS_node_jawRight', u'BS_node_jawOpen', u'BS_node_mouthClose', u'blendWeighted2', u'blendWeighted3', u'BS_node_mouthRight', u'BS_node_mouthLeft', u'BS_node_mouthSmileLeft', u'BS_node_mouthSmileRight', u'BS_node_mouthFrownRight', u'BS_node_mouthFrownLeft', u'BS_node_mouthDimpleLeft', u'BS_node_mouthDimpleRight', u'BS_node_mouthStretchLeft', u'BS_node_mouthStretchRight', u'BS_node_mouthRollLower', u'BS_node_mouthRollUpper', u'blendWeighted4', u'BS_node_mouthShrugUpper', u'BS_node_mouthLowerDownLeft', u'BS_node_mouthLowerDownRight', u'BS_node_mouthUpperUpLeft', u'BS_node_mouthUpperUpRight', u'BS_node_browDownLeft1', u'BS_node_browDownRight', u'BS_node_browInnerUp', u'BS_node_browOuterUpLeft1', u'BS_node_browOuterUpRight', u'BS_node_cheekPuff', u'BS_node_cheekSquintLeft', u'blendWeighted1', u'BS_node_noseSneerLeft', u'BS_node_noseSneerRight', u'BS_node_tongueOut']

# Snappers와 똑같은 리스트임
sliders_list = [
    "NoseWrinklerCntr_L",
    "UprLipRaiserCntr_L",
    "NlDeepenerCntr_L",
    "CornerRaiserCntr_L",
    "CornerPullerCntr_L",
    "DimplerCntr_L",
    "StretcherCntr_L",
    "CornerDepressorCntr_L",
    "LwrLipDepressorCntr_L",
    "ChinRaiserCntr_L",
    "UprLipDepressorCntr_L",
    "TightnerTCntr_L",
    "PuckererTCntr_L",
    "FunnelerTCntr_L",
    "PuckererBCntr_L",
    "TightnerBCntr_L",
    "FunnelerBCntr_L",
    "PressorCntr_L",
    "SquinterCntr_L",
    "CheekRaiserCntr_L",
    "EyeTightnerCntr_L",
    "EyeopenerCntr_L",
    "BrowDownCntr_L",
    "BrowSqueezerCntr_L",
    "BrowInRaiserCntr_L",
    "BrowOutRaiserCntr_L",
    "NeckTensionCntr_L",
    "TightnerTCntr_R",
    "UprLipDepressorCntr_R",
    "ChinRaiserCntr_R",
    "LwrLipDepressorCntr_R",
    "CornerDepressorCntr_R",
    "StretcherCntr_R",
    "DimplerCntr_R",
    "NlDeepenerCntr_R",
    "UprLipRaiserCntr_R",
    "NoseWrinklerCntr_R",
    "CornerRaiserCntr_R",
    "CornerPullerCntr_R",
    "FunnelerTCntr_R",
    "PuckererTCntr_R",
    "TightnerBCntr_R",
    "PuckererBCntr_R",
    "BrowOutRaiserCntr_R",
    "BrowInRaiserCntr_R",
    "BrowSqueezerCntr_R",
    "BrowDownCntr_R",
    "EyeopenerCntr_R",
    "EyeTightnerCntr_R",
    "SquinterCntr_R",
    "CheekRaiserCntr_R",
    "PressorCntr_R",
    "FunnelerBCntr_R",
    "NeckTensionCntr_R",
    "HeadSkinSlideCntr",
    "AdamsAppleCntr",
    "MouthCntr",
    "NoseCntr",
    "JawCntr",
    "EyeCntr",
    "EyeCntr_L",
    "EyeCntr_R",
    "Tongue1Cntr",
    "Tongue2Cntr",
    "Tongue3Cntr"]
slider_attr_list = [
    ['JawCntr' , ['JawClench_L', 'JawClench_R']],
    ['MouthCntr' , ['LwrLip_L_ML_offset', 'LwrLip_R_ML_offset', 'MouthCorner_L_ML_offset', 'MouthCorner_R_ML_offset', 'UprLip_L_ML_offset', 'UprLip_R_ML_offset', 'Nostril_L_ML_offset', 'Nostril_R_ML_offset', 'Cheek_L_ML_offset', 'Cheek_R_ML_offset', 'LwrLip_L_MR_offset', 'LwrLip_R_MR_offset', 'MouthCorner_L_MR_offset', 'MouthCorner_R_MR_offset', 'UprLip_L_MR_offset', 'UprLip_R_MR_offset', 'Nostril_L_MR_offset', 'Nostril_R_MR_offset', 'Cheek_L_MR_offset', 'Cheek_R_MR_offset', 'LwrLipLR', 'UprLipLR']],
    ['NeckTensionCntr_R' , ['NeckMuscle', 'NeckBlow', 'NeckSlide']],
    ['NeckTensionCntr_L' , ['NeckMuscle', 'NeckBlow', 'NeckSlide']],
    ['FunnelerBCntr_R' , ['Forward', 'LipBack', 'LipVolume', 'LipRoll', 'LwrLip_offset', 'MouthCorner_offset']],
    ['CheekRaiserCntr_R' , ['Cheek_offset', 'LwrLid_offset', 'Brow_offset']],
    ['EyeopenerCntr_R' , ['Blink']],
    ['BrowSqueezerCntr_R' , ['Lower']],
    ['SquinterCntr_R' , ['LwrLidUpDn']],
    ['EyeTightnerCntr_R' , ['Squeeze']],
    ['PuckererBCntr_R' , ['MouthCorner_offset', 'LwrLip_offset', 'Cheek_offset']],
    ['TightnerBCntr_R' , ['MouthCorner_offset', 'LwrLip_offset', 'Cheek_offset']],
    ['CornerPullerCntr_R' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Cheek_offset', 'NasoBulge_offset', 'Nostril_offset', 'LwrLid_offset']],
    ['CornerRaiserCntr_R' , ['LwrLip_offset', 'MouthCorner_offset', 'Cheek_offset']],
    ['PuckererTCntr_R' , ['MouthCorner_offset', 'UprLip_offset', 'Cheek_offset']],
    ['FunnelerTCntr_R' , ['Forward', 'LipBack', 'LipVolume', 'MouthCorner_offset', 'UprLip_offset', 'LipRoll']],
    ['NoseWrinklerCntr_R' , ['NoseOpenClose', 'UprLip_offset', 'NasoBulge_offset', 'Nostril_offset', 'Nose_offset', 'LwrLid_offset']],
    ['UprLipRaiserCntr_R' , ['MouthCorner_offset', 'UprLip_offset', 'NasoBulge_offset', 'Nostril_offset', 'LwrLid_offset']],
    ['StretcherCntr_R' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Nostril_offset', 'Cheek_offset', 'Chin_offset']],
    ['CornerDepressorCntr_R' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset']],
    ['NlDeepenerCntr_R' , ['NasoBulge_offset', 'Nostril_offset']],
    ['DimplerCntr_R' , ['Suck', 'CheekBlowT', 'CheekBlowB', 'StickyLips', 'Stickiness', 'StickinessSpeed', 'CornerRound', 'InflateIn', 'InflateOut', 'LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Cheek_offset', 'NarrowWide']],
    ['TightnerTCntr_R' , ['MouthCorner_offset', 'UprLip_offset']],
    ['LwrLipDepressorCntr_R' , ['Chin_offset', 'MouthCorner_offset', 'LwrLip_offset']],
    ['ChinRaiserCntr_R' , ['LipLock', 'ChinTension', 'ChinDepress', 'LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Flatten']],
    ['EyeopenerCntr_L' , ['Blink']],
    ['EyeTightnerCntr_L' , ['Squeeze']],
    ['CheekRaiserCntr_L' , ['Cheek_offset', 'LwrLid_offset', 'Brow_offset']],
    ['BrowSqueezerCntr_L' , ['Lower']],
    ['FunnelerBCntr_L' , ['Forward', 'LipBack', 'LipVolume', 'LipRoll', 'LwrLip_offset', 'MouthCorner_offset']],
    ['TightnerBCntr_L' , ['MouthCorner_offset', 'LwrLip_offset', 'Cheek_offset']],
    ['SquinterCntr_L' , ['LwrLidUpDn']],
    ['PuckererBCntr_L' , ['MouthCorner_offset', 'LwrLip_offset', 'Cheek_offset']],
    ['FunnelerTCntr_L' , ['Forward', 'LipBack', 'LipVolume', 'MouthCorner_offset', 'UprLip_offset', 'LipRoll']],
    ['ChinRaiserCntr_L' , ['LipLock', 'ChinTension', 'ChinDepress', 'LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Flatten']],
    ['PuckererTCntr_L' , ['MouthCorner_offset', 'UprLip_offset', 'Cheek_offset']],
    ['TightnerTCntr_L' , ['MouthCorner_offset', 'UprLip_offset']],
    ['LwrLipDepressorCntr_L' , ['Chin_offset', 'MouthCorner_offset', 'LwrLip_offset']],
    ['CornerDepressorCntr_L' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset']],
    ['CornerPullerCntr_L' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Cheek_offset', 'NasoBulge_offset', 'Nostril_offset', 'LwrLid_offset']],
    ['CornerRaiserCntr_L' , ['LwrLip_offset', 'MouthCorner_offset', 'Cheek_offset']],
    ['StretcherCntr_L' , ['LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Nostril_offset', 'Cheek_offset', 'Chin_offset']],
    ['DimplerCntr_L' , ['Suck', 'CheekBlowT', 'CheekBlowB', 'StickyLips', 'Stickiness', 'StickinessSpeed', 'CornerRound', 'InflateIn', 'InflateOut', 'LwrLip_offset', 'MouthCorner_offset', 'UprLip_offset', 'Cheek_offset', 'NarrowWide']],
    ['NlDeepenerCntr_L' , ['NasoBulge_offset', 'Nostril_offset']],
    ['UprLipRaiserCntr_L' , ['MouthCorner_offset', 'UprLip_offset', 'NasoBulge_offset', 'Nostril_offset', 'LwrLid_offset']],
    ['NoseWrinklerCntr_L' , ['NoseOpenClose', 'UprLip_offset', 'NasoBulge_offset', 'Nostril_offset', 'Nose_offset', 'LwrLid_offset']] ]
adj_cntr_list = [
    "NostrilT_1_R_cntr",
    "NostrilT_1_L_cntr",
    "LwrLid_1_R_cntr",
    "UprLid_1_L_cntr",
    "NostrilS_1_R_cntr",
    "LwrLid_1_L_cntr",
    "UprLid_1_R_cntr",
    "NostrilS_1_L_cntr",
    "NostrilIn_1_R_cntr",
    "LwrLipMid_1_L_cntr",
    "UprLipMid_1_R_cntr",
    "NostrilIn_1_L_cntr",
    "LwrLipMid_1_R_cntr",
    "UprLipMid_2_L_cntr",
    "UprLipMid_3_R_cntr",
    "UprLipMid_1_L_cntr",
    "UprLipMid_2_R_cntr",
    "UprLipMid_3_L_cntr",
    "UprLipMid_4_R_cntr",
    "UprLipMid_4_L_cntr",
    "LwrLipMid_3_R_cntr",
    "LwrLipMid_3_L_cntr",
    "LwrLipMid_4_R_cntr",
    "LwrLipMid_4_L_cntr",
    "NoseBridgeB_1_R_cntr",
    "NoseBridgeB_1_L_cntr",
    "LwrLipMid_2_R_cntr",
    "LwrLipMid_2_L_cntr",
    "CheekBulge_1_R_cntr",
    "CheekBulge_1_L_cntr",
    "CheekBoneT_1_R_cntr",
    "CheekBoneT_1_L_cntr",
    "EyeCorner_1_R_cntr",
    "EyeCorner_1_L_cntr",
    "Cheek_1_R_cntr",
    "Cheek_1_L_cntr",
    "CheekBone_1_R_cntr",
    "CheekBone_1_L_cntr",
    "EyeBag_3_R_cntr",
    "EyeBag_3_L_cntr",
    "EyeBag_1_R_cntr",
    "EyeBag_1_L_cntr",
    "EyeFold_6_R_cntr",
    "EyeBag_2_R_cntr",
    "EyeBag_2_L_cntr",
    "EyeFold_6_L_cntr",
    "LwrLid_3_R_cntr",
    "LwrLid_2_L_cntr",
    "LwrLid_4_R_cntr",
    "LwrLid_3_L_cntr",
    "LwrLid_2_R_cntr",
    "UprLid_5_L_cntr",
    "UprLid_2_R_cntr",
    "LwrLid_4_L_cntr",
    "UprLid_5_R_cntr",
    "UprLid_2_L_cntr",
    "UprLid_3_R_cntr",
    "BrowOut_2_L_cntr",
    "BrowT_4_R_cntr",
    "UprLid_3_L_cntr",
    "BrowOut_2_R_cntr",
    "BrowT_4_L_cntr",
    "BrowT_3_R_cntr",
    "BrowT_1_L_cntr",
    "BrowT_2_R_cntr",
    "BrowT_3_L_cntr",
    "BrowT_1_R_cntr",
    "BrowB_4_R_cntr",
    "BrowB_4_L_cntr",
    "BrowT_2_L_cntr",
    "BrowB_1_R_cntr",
    "BrowB_1_L_cntr",
    "BrowB_3_R_cntr",
    "BrowB_3_L_cntr",
    "Brow_3_R_cntr",
    "Brow_3_L_cntr",
    "Brow_4_R_cntr",
    "Brow_4_L_cntr",
    "EyeFold_1_R_cntr",
    "EyeFold_1_L_cntr",
    "Brow_2_R_cntr",
    "Brow_2_L_cntr",
    "EyeFold_4_R_cntr",
    "EyeFold_4_L_cntr",
    "EyeFold_2_R_cntr",
    "EyeFold_2_L_cntr",
    "EyeFold_3_R_cntr",
    "EyeFold_3_L_cntr",
    "BrowB_2_R_cntr",
    "BrowB_2_L_cntr",
    "EyeCavity_1_R_cntr",
    "EyeCavity_1_L_cntr",
    "NoseBridgeT_1_R_cntr",
    "Brow_1_R_cntr",
    "Brow_1_L_cntr",
    "NoseBridgeT_1_L_cntr",
    "NoseBridge_1_R_cntr",
    "UprLipIn_1_L_cntr",
    "UprLipIn_2_R_cntr",
    "NoseBridge_1_L_cntr",
    "UprLipIn_1_R_cntr",
    "UprLipIn_3_L_cntr",
    "LwrLipIn_2_R_cntr",
    "UprLipIn_2_L_cntr",
    "UprLipIn_3_R_cntr",
    "LwrLipIn_2_L_cntr",
    "LwrLipIn_1_R_cntr",
    "LwrLipIn_1_L_cntr",
    "LwrLipIn_3_R_cntr",
    "LwrLipIn_3_L_cntr",
    "LwrLip_3_R_cntr",
    "MouthCornerInB_1_L_cntr",
    "LwrLipIn_4_R_cntr",
    "LwrLip_3_L_cntr",
    "MouthCornerInB_1_R_cntr",
    "UprLipIn_4_L_cntr",
    "LwrLip_1_R_cntr",
    "LwrLip_1_L_cntr",
    "LwrLipIn_4_L_cntr",
    "UprLipIn_4_R_cntr",
    "ChinB_2_R_cntr",
    "ChinB_2_L_cntr",
    "LwrLip_2_R_cntr",
    "LwrLip_2_L_cntr",
    "ChinB_1_R_cntr",
    "ChinB_1_L_cntr",
    "ChinT_2_R_cntr",
    "ChinT_2_L_cntr",
    "Chin_1_R_cntr",
    "Chin_1_L_cntr",
    "ChinT_1_R_cntr",
    "ChinT_1_L_cntr",
    "LwrLipB_1_R_cntr",
    "LwrLipB_1_L_cntr",
    "LwrLipB_2_R_cntr",
    "LwrLipB_2_L_cntr",
    "ChinB_3_R_cntr",
    "ChinB_3_L_cntr",
    "UnderChin_1_R_cntr",
    "UnderChin_1_L_cntr",
    "EyeFold_5_R_cntr",
    "EyeFold_5_L_cntr",
    "UprLid_4_R_cntr",
    "LwrLip_4_R_cntr",
    "LwrLip_4_L_cntr",
    "UprLid_4_L_cntr",
    "EyeFoldB_1_R_cntr",
    "BrowOut_1_L_cntr",
    "LwrLipB_3_R_cntr",
    "EyeFoldB_1_L_cntr",
    "BrowOut_1_R_cntr",
    "LwrLipB_3_L_cntr",
    "NasoBulge_6_R_cntr",
    "NasoBulge_5_L_cntr",
    "MouthCorner_1_R_cntr",
    "NasoBulge_6_L_cntr",
    "NasoBulge_5_R_cntr",
    "CheekBulge_2_L_cntr",
    "CheekBulge_3_R_cntr",
    "MouthCorner_1_L_cntr",
    "CheekBulge_2_R_cntr",
    "CheekBulge_3_L_cntr",
    "CheekBulge_6_R_cntr",
    "CheekBulge_4_L_cntr",
    "CheekBulge_5_R_cntr",
    "CheekBulge_6_L_cntr",
    "CheekBulge_4_R_cntr",
    "CheekBulge_5_L_cntr",
    "NasoBulge_2_R_cntr",
    "NasoBulge_2_L_cntr",
    "NasoCavity_1_R_cntr",
    "NasoCavity_1_L_cntr",
    "MouthCornerOut_1_R_cntr",
    "MouthCornerOut_1_L_cntr",
    "UprLip_3_R_cntr",
    "UprLip_3_L_cntr",
    "MouthCornerInT_1_R_cntr",
    "MouthCornerInT_1_L_cntr",
    "UprLip_4_R_cntr",
    "UprLip_4_L_cntr",
    "UprLip_2_R_cntr",
    "UprLip_2_L_cntr",
    "UprLipT_3_R_cntr",
    "UprLipT_3_L_cntr",
    "UprLip_1_R_cntr",
    "UprLip_1_L_cntr",
    "UprLipT_2_R_cntr",
    "UprLipT_2_L_cntr",
    "UprLipT_4_R_cntr",
    "UprLipT_4_L_cntr",
    "NasoBulge_4_R_cntr",
    "NasoBulge_4_L_cntr",
    "NasoBulge_3_R_cntr",
    "UprLipT_1_R_cntr",
    "UprLipT_1_L_cntr",
    "NasoBulge_3_L_cntr",
    "NostrilOut_1_R_cntr",
    "NostrilOut_1_L_cntr",
    "NasoBulge_1_R_cntr",
    "NasoBulge_1_L_cntr",
    #"Fill_1_R_cntr",
    #"Fill_1_L_cntr",
    "Mouth_Corner_L_Parent_cntr",
    "UpperLip_2_L_Parent_cntr",
    "LowerLip_2_L_Parent_cntr",
    "UpperLip_1_L_Parent_cntr",
    "LowerLip_1_L_Parent_cntr",
    "Mouth_Corner_R_Parent_cntr",
    "UpperLip_2_R_Parent_cntr",
    "LowerLip_2_R_Parent_cntr",
    "UpperLip_1_R_Parent_cntr",
    "LowerLip_1_R_Parent_cntr"]

#['Fill_1_R_cntr', 'translateX'], ['Fill_1_R_cntr', 'translateY'], ['Fill_1_R_cntr', 'translateZ'], ['Fill_1_L_cntr', 'translateX'], ['Fill_1_L_cntr', 'translateY'], ['Fill_1_L_cntr', 'translateZ']
CntrAttrMap_list = [['NoseWrinklerCntr_L', 'translateY'], ['UprLipRaiserCntr_L', 'translateY'], ['NlDeepenerCntr_L', 'translateY'], ['CornerRaiserCntr_L', 'translateY'], ['CornerPullerCntr_L', 'translateY'], ['DimplerCntr_L', 'translateY'], ['StretcherCntr_L', 'translateY'], ['CornerDepressorCntr_L', 'translateY'], ['LwrLipDepressorCntr_L', 'translateY'], ['ChinRaiserCntr_L', 'translateY'], ['UprLipDepressorCntr_L', 'translateY'], ['TightnerTCntr_L', 'translateY'], ['PuckererTCntr_L', 'translateY'], ['FunnelerTCntr_L', 'translateY'], ['PuckererBCntr_L', 'translateY'], ['TightnerBCntr_L', 'translateY'], ['FunnelerBCntr_L', 'translateY'], ['PressorCntr_L', 'translateY'], ['SquinterCntr_L', 'translateY'], ['CheekRaiserCntr_L', 'translateY'], ['EyeTightnerCntr_L', 'translateY'], ['EyeopenerCntr_L', 'translateY'], ['BrowDownCntr_L', 'translateY'], ['BrowSqueezerCntr_L', 'translateY'], ['BrowInRaiserCntr_L', 'translateY'], ['BrowOutRaiserCntr_L', 'translateY'], ['NeckTensionCntr_L', 'translateY'], ['TightnerTCntr_R', 'translateY'], ['UprLipDepressorCntr_R', 'translateY'], ['ChinRaiserCntr_R', 'translateY'], ['LwrLipDepressorCntr_R', 'translateY'], ['CornerDepressorCntr_R', 'translateY'], ['StretcherCntr_R', 'translateY'], ['DimplerCntr_R', 'translateY'], ['NlDeepenerCntr_R', 'translateY'], ['UprLipRaiserCntr_R', 'translateY'], ['NoseWrinklerCntr_R', 'translateY'], ['CornerRaiserCntr_R', 'translateY'], ['CornerPullerCntr_R', 'translateY'], ['FunnelerTCntr_R', 'translateY'], ['PuckererTCntr_R', 'translateY'], ['TightnerBCntr_R', 'translateY'], ['PuckererBCntr_R', 'translateY'], ['BrowOutRaiserCntr_R', 'translateY'], ['BrowInRaiserCntr_R', 'translateY'], ['BrowSqueezerCntr_R', 'translateY'], ['BrowDownCntr_R', 'translateY'], ['EyeopenerCntr_R', 'translateY'], ['EyeTightnerCntr_R', 'translateY'], ['SquinterCntr_R', 'translateY'], ['CheekRaiserCntr_R', 'translateY'], ['PressorCntr_R', 'translateY'], ['FunnelerBCntr_R', 'translateY'], ['NeckTensionCntr_R', 'translateY'], ['HeadSkinSlideCntr', 'translateY'], ['AdamsAppleCntr', 'translateY'], ['MouthCntr', 'translateY'], ['NoseCntr', 'translateX'], ['NoseCntr', 'translateY'], ['NoseCntr', 'translateZ'], ['JawCntr', 'translateX'], ['JawCntr', 'translateY'], ['JawCntr', 'translateZ'], ['EyeCntr', 'translateX'], ['EyeCntr', 'translateY'], ['EyeCntr', 'translateZ'], ['EyeCntr_L', 'translateX'], ['EyeCntr_L', 'translateY'], ['EyeCntr_L', 'translateZ'], ['EyeCntr_R', 'translateX'], ['EyeCntr_R', 'translateY'], ['EyeCntr_R', 'translateZ'], ['Tongue1Cntr', 'translateX'], ['Tongue1Cntr', 'translateY'], ['Tongue1Cntr', 'translateZ'], ['Tongue2Cntr', 'translateX'], ['Tongue2Cntr', 'translateY'], ['Tongue2Cntr', 'translateZ'], ['Tongue3Cntr', 'translateX'], ['Tongue3Cntr', 'translateY'], ['Tongue3Cntr', 'translateZ'], ['NostrilT_1_R_cntr', 'translateX'], ['NostrilT_1_R_cntr', 'translateY'], ['NostrilT_1_R_cntr', 'translateZ'], ['NostrilT_1_L_cntr', 'translateX'], ['NostrilT_1_L_cntr', 'translateY'], ['NostrilT_1_L_cntr', 'translateZ'], ['LwrLid_1_R_cntr', 'translateX'], ['LwrLid_1_R_cntr', 'translateY'], ['LwrLid_1_R_cntr', 'translateZ'], ['UprLid_1_L_cntr', 'translateX'], ['UprLid_1_L_cntr', 'translateY'], ['UprLid_1_L_cntr', 'translateZ'], ['NostrilS_1_R_cntr', 'translateX'], ['NostrilS_1_R_cntr', 'translateY'], ['NostrilS_1_R_cntr', 'translateZ'], ['LwrLid_1_L_cntr', 'translateX'], ['LwrLid_1_L_cntr', 'translateY'], ['LwrLid_1_L_cntr', 'translateZ'], ['UprLid_1_R_cntr', 'translateX'], ['UprLid_1_R_cntr', 'translateY'], ['UprLid_1_R_cntr', 'translateZ'], ['NostrilS_1_L_cntr', 'translateX'], ['NostrilS_1_L_cntr', 'translateY'], ['NostrilS_1_L_cntr', 'translateZ'], ['NostrilIn_1_R_cntr', 'translateX'], ['NostrilIn_1_R_cntr', 'translateY'], ['NostrilIn_1_R_cntr', 'translateZ'], ['LwrLipMid_1_L_cntr', 'translateX'], ['LwrLipMid_1_L_cntr', 'translateY'], ['LwrLipMid_1_L_cntr', 'translateZ'], ['UprLipMid_1_R_cntr', 'translateX'], ['UprLipMid_1_R_cntr', 'translateY'], ['UprLipMid_1_R_cntr', 'translateZ'], ['NostrilIn_1_L_cntr', 'translateX'], ['NostrilIn_1_L_cntr', 'translateY'], ['NostrilIn_1_L_cntr', 'translateZ'], ['LwrLipMid_1_R_cntr', 'translateX'], ['LwrLipMid_1_R_cntr', 'translateY'], ['LwrLipMid_1_R_cntr', 'translateZ'], ['UprLipMid_2_L_cntr', 'translateX'], ['UprLipMid_2_L_cntr', 'translateY'], ['UprLipMid_2_L_cntr', 'translateZ'], ['UprLipMid_3_R_cntr', 'translateX'], ['UprLipMid_3_R_cntr', 'translateY'], ['UprLipMid_3_R_cntr', 'translateZ'], ['UprLipMid_1_L_cntr', 'translateX'], ['UprLipMid_1_L_cntr', 'translateY'], ['UprLipMid_1_L_cntr', 'translateZ'], ['UprLipMid_2_R_cntr', 'translateX'], ['UprLipMid_2_R_cntr', 'translateY'], ['UprLipMid_2_R_cntr', 'translateZ'], ['UprLipMid_3_L_cntr', 'translateX'], ['UprLipMid_3_L_cntr', 'translateY'], ['UprLipMid_3_L_cntr', 'translateZ'], ['UprLipMid_4_R_cntr', 'translateX'], ['UprLipMid_4_R_cntr', 'translateY'], ['UprLipMid_4_R_cntr', 'translateZ'], ['UprLipMid_4_L_cntr', 'translateX'], ['UprLipMid_4_L_cntr', 'translateY'], ['UprLipMid_4_L_cntr', 'translateZ'], ['LwrLipMid_3_R_cntr', 'translateX'], ['LwrLipMid_3_R_cntr', 'translateY'], ['LwrLipMid_3_R_cntr', 'translateZ'], ['LwrLipMid_3_L_cntr', 'translateX'], ['LwrLipMid_3_L_cntr', 'translateY'], ['LwrLipMid_3_L_cntr', 'translateZ'], ['LwrLipMid_4_R_cntr', 'translateX'], ['LwrLipMid_4_R_cntr', 'translateY'], ['LwrLipMid_4_R_cntr', 'translateZ'], ['LwrLipMid_4_L_cntr', 'translateX'], ['LwrLipMid_4_L_cntr', 'translateY'], ['LwrLipMid_4_L_cntr', 'translateZ'], ['NoseBridgeB_1_R_cntr', 'translateX'], ['NoseBridgeB_1_R_cntr', 'translateY'], ['NoseBridgeB_1_R_cntr', 'translateZ'], ['NoseBridgeB_1_L_cntr', 'translateX'], ['NoseBridgeB_1_L_cntr', 'translateY'], ['NoseBridgeB_1_L_cntr', 'translateZ'], ['LwrLipMid_2_R_cntr', 'translateX'], ['LwrLipMid_2_R_cntr', 'translateY'], ['LwrLipMid_2_R_cntr', 'translateZ'], ['LwrLipMid_2_L_cntr', 'translateX'], ['LwrLipMid_2_L_cntr', 'translateY'], ['LwrLipMid_2_L_cntr', 'translateZ'], ['CheekBulge_1_R_cntr', 'translateX'], ['CheekBulge_1_R_cntr', 'translateY'], ['CheekBulge_1_R_cntr', 'translateZ'], ['CheekBulge_1_L_cntr', 'translateX'], ['CheekBulge_1_L_cntr', 'translateY'], ['CheekBulge_1_L_cntr', 'translateZ'], ['CheekBoneT_1_R_cntr', 'translateX'], ['CheekBoneT_1_R_cntr', 'translateY'], ['CheekBoneT_1_R_cntr', 'translateZ'], ['CheekBoneT_1_L_cntr', 'translateX'], ['CheekBoneT_1_L_cntr', 'translateY'], ['CheekBoneT_1_L_cntr', 'translateZ'], ['EyeCorner_1_R_cntr', 'translateX'], ['EyeCorner_1_R_cntr', 'translateY'], ['EyeCorner_1_R_cntr', 'translateZ'], ['EyeCorner_1_L_cntr', 'translateX'], ['EyeCorner_1_L_cntr', 'translateY'], ['EyeCorner_1_L_cntr', 'translateZ'], ['Cheek_1_R_cntr', 'translateX'], ['Cheek_1_R_cntr', 'translateY'], ['Cheek_1_R_cntr', 'translateZ'], ['Cheek_1_L_cntr', 'translateX'], ['Cheek_1_L_cntr', 'translateY'], ['Cheek_1_L_cntr', 'translateZ'], ['CheekBone_1_R_cntr', 'translateX'], ['CheekBone_1_R_cntr', 'translateY'], ['CheekBone_1_R_cntr', 'translateZ'], ['CheekBone_1_L_cntr', 'translateX'], ['CheekBone_1_L_cntr', 'translateY'], ['CheekBone_1_L_cntr', 'translateZ'], ['EyeBag_3_R_cntr', 'translateX'], ['EyeBag_3_R_cntr', 'translateY'], ['EyeBag_3_R_cntr', 'translateZ'], ['EyeBag_3_L_cntr', 'translateX'], ['EyeBag_3_L_cntr', 'translateY'], ['EyeBag_3_L_cntr', 'translateZ'], ['EyeBag_1_R_cntr', 'translateX'], ['EyeBag_1_R_cntr', 'translateY'], ['EyeBag_1_R_cntr', 'translateZ'], ['EyeBag_1_L_cntr', 'translateX'], ['EyeBag_1_L_cntr', 'translateY'], ['EyeBag_1_L_cntr', 'translateZ'], ['EyeFold_6_R_cntr', 'translateX'], ['EyeFold_6_R_cntr', 'translateY'], ['EyeFold_6_R_cntr', 'translateZ'], ['EyeBag_2_R_cntr', 'translateX'], ['EyeBag_2_R_cntr', 'translateY'], ['EyeBag_2_R_cntr', 'translateZ'], ['EyeBag_2_L_cntr', 'translateX'], ['EyeBag_2_L_cntr', 'translateY'], ['EyeBag_2_L_cntr', 'translateZ'], ['EyeFold_6_L_cntr', 'translateX'], ['EyeFold_6_L_cntr', 'translateY'], ['EyeFold_6_L_cntr', 'translateZ'], ['LwrLid_3_R_cntr', 'translateX'], ['LwrLid_3_R_cntr', 'translateY'], ['LwrLid_3_R_cntr', 'translateZ'], ['LwrLid_2_L_cntr', 'translateX'], ['LwrLid_2_L_cntr', 'translateY'], ['LwrLid_2_L_cntr', 'translateZ'], ['LwrLid_4_R_cntr', 'translateX'], ['LwrLid_4_R_cntr', 'translateY'], ['LwrLid_4_R_cntr', 'translateZ'], ['LwrLid_3_L_cntr', 'translateX'], ['LwrLid_3_L_cntr', 'translateY'], ['LwrLid_3_L_cntr', 'translateZ'], ['LwrLid_2_R_cntr', 'translateX'], ['LwrLid_2_R_cntr', 'translateY'], ['LwrLid_2_R_cntr', 'translateZ'], ['UprLid_5_L_cntr', 'translateX'], ['UprLid_5_L_cntr', 'translateY'], ['UprLid_5_L_cntr', 'translateZ'], ['UprLid_2_R_cntr', 'translateX'], ['UprLid_2_R_cntr', 'translateY'], ['UprLid_2_R_cntr', 'translateZ'], ['LwrLid_4_L_cntr', 'translateX'], ['LwrLid_4_L_cntr', 'translateY'], ['LwrLid_4_L_cntr', 'translateZ'], ['UprLid_5_R_cntr', 'translateX'], ['UprLid_5_R_cntr', 'translateY'], ['UprLid_5_R_cntr', 'translateZ'], ['UprLid_2_L_cntr', 'translateX'], ['UprLid_2_L_cntr', 'translateY'], ['UprLid_2_L_cntr', 'translateZ'], ['UprLid_3_R_cntr', 'translateX'], ['UprLid_3_R_cntr', 'translateY'], ['UprLid_3_R_cntr', 'translateZ'], ['BrowOut_2_L_cntr', 'translateX'], ['BrowOut_2_L_cntr', 'translateY'], ['BrowOut_2_L_cntr', 'translateZ'], ['BrowT_4_R_cntr', 'translateX'], ['BrowT_4_R_cntr', 'translateY'], ['BrowT_4_R_cntr', 'translateZ'], ['UprLid_3_L_cntr', 'translateX'], ['UprLid_3_L_cntr', 'translateY'], ['UprLid_3_L_cntr', 'translateZ'], ['BrowOut_2_R_cntr', 'translateX'], ['BrowOut_2_R_cntr', 'translateY'], ['BrowOut_2_R_cntr', 'translateZ'], ['BrowT_4_L_cntr', 'translateX'], ['BrowT_4_L_cntr', 'translateY'], ['BrowT_4_L_cntr', 'translateZ'], ['BrowT_3_R_cntr', 'translateX'], ['BrowT_3_R_cntr', 'translateY'], ['BrowT_3_R_cntr', 'translateZ'], ['BrowT_1_L_cntr', 'translateX'], ['BrowT_1_L_cntr', 'translateY'], ['BrowT_1_L_cntr', 'translateZ'], ['BrowT_2_R_cntr', 'translateX'], ['BrowT_2_R_cntr', 'translateY'], ['BrowT_2_R_cntr', 'translateZ'], ['BrowT_3_L_cntr', 'translateX'], ['BrowT_3_L_cntr', 'translateY'], ['BrowT_3_L_cntr', 'translateZ'], ['BrowT_1_R_cntr', 'translateX'], ['BrowT_1_R_cntr', 'translateY'], ['BrowT_1_R_cntr', 'translateZ'], ['BrowB_4_R_cntr', 'translateX'], ['BrowB_4_R_cntr', 'translateY'], ['BrowB_4_R_cntr', 'translateZ'], ['BrowB_4_L_cntr', 'translateX'], ['BrowB_4_L_cntr', 'translateY'], ['BrowB_4_L_cntr', 'translateZ'], ['BrowT_2_L_cntr', 'translateX'], ['BrowT_2_L_cntr', 'translateY'], ['BrowT_2_L_cntr', 'translateZ'], ['BrowB_1_R_cntr', 'translateX'], ['BrowB_1_R_cntr', 'translateY'], ['BrowB_1_R_cntr', 'translateZ'], ['BrowB_1_L_cntr', 'translateX'], ['BrowB_1_L_cntr', 'translateY'], ['BrowB_1_L_cntr', 'translateZ'], ['BrowB_3_R_cntr', 'translateX'], ['BrowB_3_R_cntr', 'translateY'], ['BrowB_3_R_cntr', 'translateZ'], ['BrowB_3_L_cntr', 'translateX'], ['BrowB_3_L_cntr', 'translateY'], ['BrowB_3_L_cntr', 'translateZ'], ['Brow_3_R_cntr', 'translateX'], ['Brow_3_R_cntr', 'translateY'], ['Brow_3_R_cntr', 'translateZ'], ['Brow_3_L_cntr', 'translateX'], ['Brow_3_L_cntr', 'translateY'], ['Brow_3_L_cntr', 'translateZ'], ['Brow_4_R_cntr', 'translateX'], ['Brow_4_R_cntr', 'translateY'], ['Brow_4_R_cntr', 'translateZ'], ['Brow_4_L_cntr', 'translateX'], ['Brow_4_L_cntr', 'translateY'], ['Brow_4_L_cntr', 'translateZ'], ['EyeFold_1_R_cntr', 'translateX'], ['EyeFold_1_R_cntr', 'translateY'], ['EyeFold_1_R_cntr', 'translateZ'], ['EyeFold_1_L_cntr', 'translateX'], ['EyeFold_1_L_cntr', 'translateY'], ['EyeFold_1_L_cntr', 'translateZ'], ['Brow_2_R_cntr', 'translateX'], ['Brow_2_R_cntr', 'translateY'], ['Brow_2_R_cntr', 'translateZ'], ['Brow_2_L_cntr', 'translateX'], ['Brow_2_L_cntr', 'translateY'], ['Brow_2_L_cntr', 'translateZ'], ['EyeFold_4_R_cntr', 'translateX'], ['EyeFold_4_R_cntr', 'translateY'], ['EyeFold_4_R_cntr', 'translateZ'], ['EyeFold_4_L_cntr', 'translateX'], ['EyeFold_4_L_cntr', 'translateY'], ['EyeFold_4_L_cntr', 'translateZ'], ['EyeFold_2_R_cntr', 'translateX'], ['EyeFold_2_R_cntr', 'translateY'], ['EyeFold_2_R_cntr', 'translateZ'], ['EyeFold_2_L_cntr', 'translateX'], ['EyeFold_2_L_cntr', 'translateY'], ['EyeFold_2_L_cntr', 'translateZ'], ['EyeFold_3_R_cntr', 'translateX'], ['EyeFold_3_R_cntr', 'translateY'], ['EyeFold_3_R_cntr', 'translateZ'], ['EyeFold_3_L_cntr', 'translateX'], ['EyeFold_3_L_cntr', 'translateY'], ['EyeFold_3_L_cntr', 'translateZ'], ['BrowB_2_R_cntr', 'translateX'], ['BrowB_2_R_cntr', 'translateY'], ['BrowB_2_R_cntr', 'translateZ'], ['BrowB_2_L_cntr', 'translateX'], ['BrowB_2_L_cntr', 'translateY'], ['BrowB_2_L_cntr', 'translateZ'], ['EyeCavity_1_R_cntr', 'translateX'], ['EyeCavity_1_R_cntr', 'translateY'], ['EyeCavity_1_R_cntr', 'translateZ'], ['EyeCavity_1_L_cntr', 'translateX'], ['EyeCavity_1_L_cntr', 'translateY'], ['EyeCavity_1_L_cntr', 'translateZ'], ['NoseBridgeT_1_R_cntr', 'translateX'], ['NoseBridgeT_1_R_cntr', 'translateY'], ['NoseBridgeT_1_R_cntr', 'translateZ'], ['Brow_1_R_cntr', 'translateX'], ['Brow_1_R_cntr', 'translateY'], ['Brow_1_R_cntr', 'translateZ'], ['Brow_1_L_cntr', 'translateX'], ['Brow_1_L_cntr', 'translateY'], ['Brow_1_L_cntr', 'translateZ'], ['NoseBridgeT_1_L_cntr', 'translateX'], ['NoseBridgeT_1_L_cntr', 'translateY'], ['NoseBridgeT_1_L_cntr', 'translateZ'], ['NoseBridge_1_R_cntr', 'translateX'], ['NoseBridge_1_R_cntr', 'translateY'], ['NoseBridge_1_R_cntr', 'translateZ'], ['UprLipIn_1_L_cntr', 'translateX'], ['UprLipIn_1_L_cntr', 'translateY'], ['UprLipIn_1_L_cntr', 'translateZ'], ['UprLipIn_2_R_cntr', 'translateX'], ['UprLipIn_2_R_cntr', 'translateY'], ['UprLipIn_2_R_cntr', 'translateZ'], ['NoseBridge_1_L_cntr', 'translateX'], ['NoseBridge_1_L_cntr', 'translateY'], ['NoseBridge_1_L_cntr', 'translateZ'], ['UprLipIn_1_R_cntr', 'translateX'], ['UprLipIn_1_R_cntr', 'translateY'], ['UprLipIn_1_R_cntr', 'translateZ'], ['UprLipIn_3_L_cntr', 'translateX'], ['UprLipIn_3_L_cntr', 'translateY'], ['UprLipIn_3_L_cntr', 'translateZ'], ['LwrLipIn_2_R_cntr', 'translateX'], ['LwrLipIn_2_R_cntr', 'translateY'], ['LwrLipIn_2_R_cntr', 'translateZ'], ['UprLipIn_2_L_cntr', 'translateX'], ['UprLipIn_2_L_cntr', 'translateY'], ['UprLipIn_2_L_cntr', 'translateZ'], ['UprLipIn_3_R_cntr', 'translateX'], ['UprLipIn_3_R_cntr', 'translateY'], ['UprLipIn_3_R_cntr', 'translateZ'], ['LwrLipIn_2_L_cntr', 'translateX'], ['LwrLipIn_2_L_cntr', 'translateY'], ['LwrLipIn_2_L_cntr', 'translateZ'], ['LwrLipIn_1_R_cntr', 'translateX'], ['LwrLipIn_1_R_cntr', 'translateY'], ['LwrLipIn_1_R_cntr', 'translateZ'], ['LwrLipIn_1_L_cntr', 'translateX'], ['LwrLipIn_1_L_cntr', 'translateY'], ['LwrLipIn_1_L_cntr', 'translateZ'], ['LwrLipIn_3_R_cntr', 'translateX'], ['LwrLipIn_3_R_cntr', 'translateY'], ['LwrLipIn_3_R_cntr', 'translateZ'], ['LwrLipIn_3_L_cntr', 'translateX'], ['LwrLipIn_3_L_cntr', 'translateY'], ['LwrLipIn_3_L_cntr', 'translateZ'], ['LwrLip_3_R_cntr', 'translateX'], ['LwrLip_3_R_cntr', 'translateY'], ['LwrLip_3_R_cntr', 'translateZ'], ['MouthCornerInB_1_L_cntr', 'translateX'], ['MouthCornerInB_1_L_cntr', 'translateY'], ['MouthCornerInB_1_L_cntr', 'translateZ'], ['LwrLipIn_4_R_cntr', 'translateX'], ['LwrLipIn_4_R_cntr', 'translateY'], ['LwrLipIn_4_R_cntr', 'translateZ'], ['LwrLip_3_L_cntr', 'translateX'], ['LwrLip_3_L_cntr', 'translateY'], ['LwrLip_3_L_cntr', 'translateZ'], ['MouthCornerInB_1_R_cntr', 'translateX'], ['MouthCornerInB_1_R_cntr', 'translateY'], ['MouthCornerInB_1_R_cntr', 'translateZ'], ['UprLipIn_4_L_cntr', 'translateX'], ['UprLipIn_4_L_cntr', 'translateY'], ['UprLipIn_4_L_cntr', 'translateZ'], ['LwrLip_1_R_cntr', 'translateX'], ['LwrLip_1_R_cntr', 'translateY'], ['LwrLip_1_R_cntr', 'translateZ'], ['LwrLip_1_L_cntr', 'translateX'], ['LwrLip_1_L_cntr', 'translateY'], ['LwrLip_1_L_cntr', 'translateZ'], ['LwrLipIn_4_L_cntr', 'translateX'], ['LwrLipIn_4_L_cntr', 'translateY'], ['LwrLipIn_4_L_cntr', 'translateZ'], ['UprLipIn_4_R_cntr', 'translateX'], ['UprLipIn_4_R_cntr', 'translateY'], ['UprLipIn_4_R_cntr', 'translateZ'], ['ChinB_2_R_cntr', 'translateX'], ['ChinB_2_R_cntr', 'translateY'], ['ChinB_2_R_cntr', 'translateZ'], ['ChinB_2_L_cntr', 'translateX'], ['ChinB_2_L_cntr', 'translateY'], ['ChinB_2_L_cntr', 'translateZ'], ['LwrLip_2_R_cntr', 'translateX'], ['LwrLip_2_R_cntr', 'translateY'], ['LwrLip_2_R_cntr', 'translateZ'], ['LwrLip_2_L_cntr', 'translateX'], ['LwrLip_2_L_cntr', 'translateY'], ['LwrLip_2_L_cntr', 'translateZ'], ['ChinB_1_R_cntr', 'translateX'], ['ChinB_1_R_cntr', 'translateY'], ['ChinB_1_R_cntr', 'translateZ'], ['ChinB_1_L_cntr', 'translateX'], ['ChinB_1_L_cntr', 'translateY'], ['ChinB_1_L_cntr', 'translateZ'], ['ChinT_2_R_cntr', 'translateX'], ['ChinT_2_R_cntr', 'translateY'], ['ChinT_2_R_cntr', 'translateZ'], ['ChinT_2_L_cntr', 'translateX'], ['ChinT_2_L_cntr', 'translateY'], ['ChinT_2_L_cntr', 'translateZ'], ['Chin_1_R_cntr', 'translateX'], ['Chin_1_R_cntr', 'translateY'], ['Chin_1_R_cntr', 'translateZ'], ['Chin_1_L_cntr', 'translateX'], ['Chin_1_L_cntr', 'translateY'], ['Chin_1_L_cntr', 'translateZ'], ['ChinT_1_R_cntr', 'translateX'], ['ChinT_1_R_cntr', 'translateY'], ['ChinT_1_R_cntr', 'translateZ'], ['ChinT_1_L_cntr', 'translateX'], ['ChinT_1_L_cntr', 'translateY'], ['ChinT_1_L_cntr', 'translateZ'], ['LwrLipB_1_R_cntr', 'translateX'], ['LwrLipB_1_R_cntr', 'translateY'], ['LwrLipB_1_R_cntr', 'translateZ'], ['LwrLipB_1_L_cntr', 'translateX'], ['LwrLipB_1_L_cntr', 'translateY'], ['LwrLipB_1_L_cntr', 'translateZ'], ['LwrLipB_2_R_cntr', 'translateX'], ['LwrLipB_2_R_cntr', 'translateY'], ['LwrLipB_2_R_cntr', 'translateZ'], ['LwrLipB_2_L_cntr', 'translateX'], ['LwrLipB_2_L_cntr', 'translateY'], ['LwrLipB_2_L_cntr', 'translateZ'], ['ChinB_3_R_cntr', 'translateX'], ['ChinB_3_R_cntr', 'translateY'], ['ChinB_3_R_cntr', 'translateZ'], ['ChinB_3_L_cntr', 'translateX'], ['ChinB_3_L_cntr', 'translateY'], ['ChinB_3_L_cntr', 'translateZ'], ['UnderChin_1_R_cntr', 'translateX'], ['UnderChin_1_R_cntr', 'translateY'], ['UnderChin_1_R_cntr', 'translateZ'], ['UnderChin_1_L_cntr', 'translateX'], ['UnderChin_1_L_cntr', 'translateY'], ['UnderChin_1_L_cntr', 'translateZ'], ['EyeFold_5_R_cntr', 'translateX'], ['EyeFold_5_R_cntr', 'translateY'], ['EyeFold_5_R_cntr', 'translateZ'], ['EyeFold_5_L_cntr', 'translateX'], ['EyeFold_5_L_cntr', 'translateY'], ['EyeFold_5_L_cntr', 'translateZ'], ['UprLid_4_R_cntr', 'translateX'], ['UprLid_4_R_cntr', 'translateY'], ['UprLid_4_R_cntr', 'translateZ'], ['LwrLip_4_R_cntr', 'translateX'], ['LwrLip_4_R_cntr', 'translateY'], ['LwrLip_4_R_cntr', 'translateZ'], ['LwrLip_4_L_cntr', 'translateX'], ['LwrLip_4_L_cntr', 'translateY'], ['LwrLip_4_L_cntr', 'translateZ'], ['UprLid_4_L_cntr', 'translateX'], ['UprLid_4_L_cntr', 'translateY'], ['UprLid_4_L_cntr', 'translateZ'], ['EyeFoldB_1_R_cntr', 'translateX'], ['EyeFoldB_1_R_cntr', 'translateY'], ['EyeFoldB_1_R_cntr', 'translateZ'], ['BrowOut_1_L_cntr', 'translateX'], ['BrowOut_1_L_cntr', 'translateY'], ['BrowOut_1_L_cntr', 'translateZ'], ['LwrLipB_3_R_cntr', 'translateX'], ['LwrLipB_3_R_cntr', 'translateY'], ['LwrLipB_3_R_cntr', 'translateZ'], ['EyeFoldB_1_L_cntr', 'translateX'], ['EyeFoldB_1_L_cntr', 'translateY'], ['EyeFoldB_1_L_cntr', 'translateZ'], ['BrowOut_1_R_cntr', 'translateX'], ['BrowOut_1_R_cntr', 'translateY'], ['BrowOut_1_R_cntr', 'translateZ'], ['LwrLipB_3_L_cntr', 'translateX'], ['LwrLipB_3_L_cntr', 'translateY'], ['LwrLipB_3_L_cntr', 'translateZ'], ['NasoBulge_6_R_cntr', 'translateX'], ['NasoBulge_6_R_cntr', 'translateY'], ['NasoBulge_6_R_cntr', 'translateZ'], ['NasoBulge_5_L_cntr', 'translateX'], ['NasoBulge_5_L_cntr', 'translateY'], ['NasoBulge_5_L_cntr', 'translateZ'], ['MouthCorner_1_R_cntr', 'translateX'], ['MouthCorner_1_R_cntr', 'translateY'], ['MouthCorner_1_R_cntr', 'translateZ'], ['NasoBulge_6_L_cntr', 'translateX'], ['NasoBulge_6_L_cntr', 'translateY'], ['NasoBulge_6_L_cntr', 'translateZ'], ['NasoBulge_5_R_cntr', 'translateX'], ['NasoBulge_5_R_cntr', 'translateY'], ['NasoBulge_5_R_cntr', 'translateZ'], ['CheekBulge_2_L_cntr', 'translateX'], ['CheekBulge_2_L_cntr', 'translateY'], ['CheekBulge_2_L_cntr', 'translateZ'], ['CheekBulge_3_R_cntr', 'translateX'], ['CheekBulge_3_R_cntr', 'translateY'], ['CheekBulge_3_R_cntr', 'translateZ'], ['MouthCorner_1_L_cntr', 'translateX'], ['MouthCorner_1_L_cntr', 'translateY'], ['MouthCorner_1_L_cntr', 'translateZ'], ['CheekBulge_2_R_cntr', 'translateX'], ['CheekBulge_2_R_cntr', 'translateY'], ['CheekBulge_2_R_cntr', 'translateZ'], ['CheekBulge_3_L_cntr', 'translateX'], ['CheekBulge_3_L_cntr', 'translateY'], ['CheekBulge_3_L_cntr', 'translateZ'], ['CheekBulge_6_R_cntr', 'translateX'], ['CheekBulge_6_R_cntr', 'translateY'], ['CheekBulge_6_R_cntr', 'translateZ'], ['CheekBulge_4_L_cntr', 'translateX'], ['CheekBulge_4_L_cntr', 'translateY'], ['CheekBulge_4_L_cntr', 'translateZ'], ['CheekBulge_5_R_cntr', 'translateX'], ['CheekBulge_5_R_cntr', 'translateY'], ['CheekBulge_5_R_cntr', 'translateZ'], ['CheekBulge_6_L_cntr', 'translateX'], ['CheekBulge_6_L_cntr', 'translateY'], ['CheekBulge_6_L_cntr', 'translateZ'], ['CheekBulge_4_R_cntr', 'translateX'], ['CheekBulge_4_R_cntr', 'translateY'], ['CheekBulge_4_R_cntr', 'translateZ'], ['CheekBulge_5_L_cntr', 'translateX'], ['CheekBulge_5_L_cntr', 'translateY'], ['CheekBulge_5_L_cntr', 'translateZ'], ['NasoBulge_2_R_cntr', 'translateX'], ['NasoBulge_2_R_cntr', 'translateY'], ['NasoBulge_2_R_cntr', 'translateZ'], ['NasoBulge_2_L_cntr', 'translateX'], ['NasoBulge_2_L_cntr', 'translateY'], ['NasoBulge_2_L_cntr', 'translateZ'], ['NasoCavity_1_R_cntr', 'translateX'], ['NasoCavity_1_R_cntr', 'translateY'], ['NasoCavity_1_R_cntr', 'translateZ'], ['NasoCavity_1_L_cntr', 'translateX'], ['NasoCavity_1_L_cntr', 'translateY'], ['NasoCavity_1_L_cntr', 'translateZ'], ['MouthCornerOut_1_R_cntr', 'translateX'], ['MouthCornerOut_1_R_cntr', 'translateY'], ['MouthCornerOut_1_R_cntr', 'translateZ'], ['MouthCornerOut_1_L_cntr', 'translateX'], ['MouthCornerOut_1_L_cntr', 'translateY'], ['MouthCornerOut_1_L_cntr', 'translateZ'], ['UprLip_3_R_cntr', 'translateX'], ['UprLip_3_R_cntr', 'translateY'], ['UprLip_3_R_cntr', 'translateZ'], ['UprLip_3_L_cntr', 'translateX'], ['UprLip_3_L_cntr', 'translateY'], ['UprLip_3_L_cntr', 'translateZ'], ['MouthCornerInT_1_R_cntr', 'translateX'], ['MouthCornerInT_1_R_cntr', 'translateY'], ['MouthCornerInT_1_R_cntr', 'translateZ'], ['MouthCornerInT_1_L_cntr', 'translateX'], ['MouthCornerInT_1_L_cntr', 'translateY'], ['MouthCornerInT_1_L_cntr', 'translateZ'], ['UprLip_4_R_cntr', 'translateX'], ['UprLip_4_R_cntr', 'translateY'], ['UprLip_4_R_cntr', 'translateZ'], ['UprLip_4_L_cntr', 'translateX'], ['UprLip_4_L_cntr', 'translateY'], ['UprLip_4_L_cntr', 'translateZ'], ['UprLip_2_R_cntr', 'translateX'], ['UprLip_2_R_cntr', 'translateY'], ['UprLip_2_R_cntr', 'translateZ'], ['UprLip_2_L_cntr', 'translateX'], ['UprLip_2_L_cntr', 'translateY'], ['UprLip_2_L_cntr', 'translateZ'], ['UprLipT_3_R_cntr', 'translateX'], ['UprLipT_3_R_cntr', 'translateY'], ['UprLipT_3_R_cntr', 'translateZ'], ['UprLipT_3_L_cntr', 'translateX'], ['UprLipT_3_L_cntr', 'translateY'], ['UprLipT_3_L_cntr', 'translateZ'], ['UprLip_1_R_cntr', 'translateX'], ['UprLip_1_R_cntr', 'translateY'], ['UprLip_1_R_cntr', 'translateZ'], ['UprLip_1_L_cntr', 'translateX'], ['UprLip_1_L_cntr', 'translateY'], ['UprLip_1_L_cntr', 'translateZ'], ['UprLipT_2_R_cntr', 'translateX'], ['UprLipT_2_R_cntr', 'translateY'], ['UprLipT_2_R_cntr', 'translateZ'], ['UprLipT_2_L_cntr', 'translateX'], ['UprLipT_2_L_cntr', 'translateY'], ['UprLipT_2_L_cntr', 'translateZ'], ['UprLipT_4_R_cntr', 'translateX'], ['UprLipT_4_R_cntr', 'translateY'], ['UprLipT_4_R_cntr', 'translateZ'], ['UprLipT_4_L_cntr', 'translateX'], ['UprLipT_4_L_cntr', 'translateY'], ['UprLipT_4_L_cntr', 'translateZ'], ['NasoBulge_4_R_cntr', 'translateX'], ['NasoBulge_4_R_cntr', 'translateY'], ['NasoBulge_4_R_cntr', 'translateZ'], ['NasoBulge_4_L_cntr', 'translateX'], ['NasoBulge_4_L_cntr', 'translateY'], ['NasoBulge_4_L_cntr', 'translateZ'], ['NasoBulge_3_R_cntr', 'translateX'], ['NasoBulge_3_R_cntr', 'translateY'], ['NasoBulge_3_R_cntr', 'translateZ'], ['UprLipT_1_R_cntr', 'translateX'], ['UprLipT_1_R_cntr', 'translateY'], ['UprLipT_1_R_cntr', 'translateZ'], ['UprLipT_1_L_cntr', 'translateX'], ['UprLipT_1_L_cntr', 'translateY'], ['UprLipT_1_L_cntr', 'translateZ'], ['NasoBulge_3_L_cntr', 'translateX'], ['NasoBulge_3_L_cntr', 'translateY'], ['NasoBulge_3_L_cntr', 'translateZ'], ['NostrilOut_1_R_cntr', 'translateX'], ['NostrilOut_1_R_cntr', 'translateY'], ['NostrilOut_1_R_cntr', 'translateZ'], ['NostrilOut_1_L_cntr', 'translateX'], ['NostrilOut_1_L_cntr', 'translateY'], ['NostrilOut_1_L_cntr', 'translateZ'], ['NasoBulge_1_R_cntr', 'translateX'], ['NasoBulge_1_R_cntr', 'translateY'], ['NasoBulge_1_R_cntr', 'translateZ'], ['NasoBulge_1_L_cntr', 'translateX'], ['NasoBulge_1_L_cntr', 'translateY'], ['NasoBulge_1_L_cntr', 'translateZ'], ['Mouth_Corner_L_Parent_cntr', 'translateX'], ['Mouth_Corner_L_Parent_cntr', 'translateY'], ['Mouth_Corner_L_Parent_cntr', 'translateZ'], ['UpperLip_2_L_Parent_cntr', 'translateX'], ['UpperLip_2_L_Parent_cntr', 'translateY'], ['UpperLip_2_L_Parent_cntr', 'translateZ'], ['LowerLip_2_L_Parent_cntr', 'translateX'], ['LowerLip_2_L_Parent_cntr', 'translateY'], ['LowerLip_2_L_Parent_cntr', 'translateZ'], ['UpperLip_1_L_Parent_cntr', 'translateX'], ['UpperLip_1_L_Parent_cntr', 'translateY'], ['UpperLip_1_L_Parent_cntr', 'translateZ'], ['LowerLip_1_L_Parent_cntr', 'translateX'], ['LowerLip_1_L_Parent_cntr', 'translateY'], ['LowerLip_1_L_Parent_cntr', 'translateZ'], ['Mouth_Corner_R_Parent_cntr', 'translateX'], ['Mouth_Corner_R_Parent_cntr', 'translateY'], ['Mouth_Corner_R_Parent_cntr', 'translateZ'], ['UpperLip_2_R_Parent_cntr', 'translateX'], ['UpperLip_2_R_Parent_cntr', 'translateY'], ['UpperLip_2_R_Parent_cntr', 'translateZ'], ['LowerLip_2_R_Parent_cntr', 'translateX'], ['LowerLip_2_R_Parent_cntr', 'translateY'], ['LowerLip_2_R_Parent_cntr', 'translateZ'], ['UpperLip_1_R_Parent_cntr', 'translateX'], ['UpperLip_1_R_Parent_cntr', 'translateY'], ['UpperLip_1_R_Parent_cntr', 'translateZ'], ['LowerLip_1_R_Parent_cntr', 'translateX'], ['LowerLip_1_R_Parent_cntr', 'translateY'], ['LowerLip_1_R_Parent_cntr', 'translateZ'],
                    ['JawCntr', 'JawClench_L'],
                    ['JawCntr', 'JawClench_R'],
                    ['MouthCntr', 'LwrLipLR'],
                    ['MouthCntr', 'UprLipLR'],
                    ['NeckTensionCntr_R', 'NeckMuscle'],
                    ['NeckTensionCntr_R', 'NeckBlow'],
                    ['NeckTensionCntr_R', 'NeckSlide'],
                    ['NeckTensionCntr_L', 'NeckMuscle'],
                    ['NeckTensionCntr_L', 'NeckBlow'],
                    ['NeckTensionCntr_L', 'NeckSlide'],
                    ['FunnelerBCntr_R', 'Forward'],
                    ['FunnelerBCntr_R', 'LipBack'],
                    ['FunnelerBCntr_R', 'LipVolume'],
                    ['FunnelerBCntr_R', 'LipRoll'],
                    ['EyeopenerCntr_R', 'Blink'],
                    ['BrowSqueezerCntr_R', 'Lower'],
                    ['SquinterCntr_R', 'LwrLidUpDn'],
                    ['EyeTightnerCntr_R', 'Squeeze'],
                    ['FunnelerTCntr_R', 'Forward'],
                    ['FunnelerTCntr_R', 'LipBack'],
                    ['FunnelerTCntr_R', 'LipVolume'],
                    ['FunnelerTCntr_R', 'LipRoll'],
                    ['NoseWrinklerCntr_R', 'NoseOpenClose'],
                    ['DimplerCntr_R', 'Suck'],
                    ['DimplerCntr_R', 'CheekBlowT'],
                    ['DimplerCntr_R', 'CheekBlowB'],
                    ['DimplerCntr_R', 'StickyLips'],
                    ['DimplerCntr_R', 'Stickiness'],
                    ['DimplerCntr_R', 'StickinessSpeed'],
                    ['DimplerCntr_R', 'CornerRound'],
                    ['DimplerCntr_R', 'InflateIn'],
                    ['DimplerCntr_R', 'InflateOut'],
                    ['DimplerCntr_R', 'NarrowWide'],
                    ['ChinRaiserCntr_R', 'LipLock'],
                    ['ChinRaiserCntr_R', 'ChinTension'],
                    ['ChinRaiserCntr_R', 'ChinDepress'],
                    ['ChinRaiserCntr_R', 'Flatten'],
                    ['EyeopenerCntr_L', 'Blink'],
                    ['EyeTightnerCntr_L', 'Squeeze'],
                    ['BrowSqueezerCntr_L', 'Lower'],
                    ['FunnelerBCntr_L', 'Forward'],
                    ['FunnelerBCntr_L', 'LipBack'],
                    ['FunnelerBCntr_L', 'LipVolume'],
                    ['FunnelerBCntr_L', 'LipRoll'],
                    ['SquinterCntr_L', 'LwrLidUpDn'],
                    ['FunnelerTCntr_L', 'Forward'],
                    ['FunnelerTCntr_L', 'LipBack'],
                    ['FunnelerTCntr_L', 'LipVolume'],
                    ['FunnelerTCntr_L', 'LipRoll'],
                    ['ChinRaiserCntr_L', 'LipLock'],
                    ['ChinRaiserCntr_L', 'ChinTension'],
                    ['ChinRaiserCntr_L', 'ChinDepress'],
                    ['ChinRaiserCntr_L', 'Flatten'],
                    ['DimplerCntr_L', 'Suck'],
                    ['DimplerCntr_L', 'CheekBlowT'],
                    ['DimplerCntr_L', 'CheekBlowB'],
                    ['DimplerCntr_L', 'StickyLips'],
                    ['DimplerCntr_L', 'Stickiness'],
                    ['DimplerCntr_L', 'StickinessSpeed'],
                    ['DimplerCntr_L', 'CornerRound'],
                    ['DimplerCntr_L', 'InflateIn'],
                    ['DimplerCntr_L', 'InflateOut'],
                    ['DimplerCntr_L', 'NarrowWide'],
                    ['NoseWrinklerCntr_L', 'NoseOpenClose']
                    ]

# 스내퍼가 사용중인 블렌드쉐입 이름 620개
snappersBlendshape620 = [u'CrnPl_L', u'CrnPl_R', u'HeadSlide', u'JwBk', u'JwDrpLk', u'JwFrw', u'JwL', u'JwR', u'LwrLp_L', u'LwrLp_R', u'Strtch_L', u'Strtch_R', u'Swallow1', u'Swallow2', u'Swallow3', u'Swallow4', u'Swallow5', u'SwallowDn1', u'SwallowDn2', u'SwallowDn3', u'UprLp_L', u'UprLp_R', u'BrInDn_00_L', u'BrInDn_01_L', u'BrInDn_00_R', u'BrInDn_01_R', u'BrInRs_00_L', u'BrInRs_00_R', u'BrLr_00_L', u'BrLr_01_L', u'BrLr_00_R', u'BrLr_01_R', u'BrOutDn_00_L', u'BrOutDn_01_L', u'BrOutDn_00_R', u'BrOutDn_01_R', u'BrOutRs_00_L', u'BrOutRs_00_R', u'ChkRs_00_L', u'ChkRs_01_L', u'ChkRs_02_L', u'ChkRs_03_L', u'ChkRs_00_R', u'ChkRs_01_R', u'ChkRs_02_R', u'ChkRs_03_R', u'ChnDprs_00_L', u'ChnDprs_00_R', u'ChnRs_00_L', u'ChnRs_01_L', u'ChnRs_02_L', u'ChnRs_03_L', u'ChnRs_04_L', u'ChnRs_05_L', u'ChnRs_06_L', u'ChnRs_07_L', u'ChnRs_08_L', u'ChnRs_00_R', u'ChnRs_01_R', u'ChnRs_02_R', u'ChnRs_03_R', u'ChnRs_04_R', u'ChnRs_05_R', u'ChnRs_06_R', u'ChnRs_07_R', u'ChnRs_08_R', u'ChnTns_00_L', u'ChnTns_00_R', u'CrnDprs_00_L', u'CrnDprs_01_L', u'CrnDprs_02_L', u'CrnDprs_03_L', u'CrnDprs_04_L', u'CrnDprs_00_R', u'CrnDprs_01_R', u'CrnDprs_02_R', u'CrnDprs_03_R', u'CrnDprs_04_R', u'CrnPl_00_L', u'CrnPl_01_L', u'CrnPl_02_L', u'CrnPl_03_L', u'CrnPl_04_L', u'CrnPl_05_L', u'CrnPl_06_L', u'CrnPl_07_L', u'CrnPl_08_L', u'CrnPl_09_L', u'CrnPl_10_L', u'CrnPl_11_L', u'CrnPl_12_L', u'CrnPl_13_L', u'CrnPl_14_L', u'CrnPl_00_R', u'CrnPl_01_R', u'CrnPl_02_R', u'CrnPl_03_R', u'CrnPl_04_R', u'CrnPl_05_R', u'CrnPl_06_R', u'CrnPl_07_R', u'CrnPl_08_R', u'CrnPl_09_R', u'CrnPl_10_R', u'CrnPl_11_R', u'CrnPl_12_R', u'CrnPl_13_R', u'CrnPl_14_R', u'CrnRnd_00_L', u'CrnRnd_00_R', u'CrnRs_00_L', u'CrnRs_01_L', u'CrnRs_02_L', u'CrnRs_03_L', u'CrnRs_04_L', u'CrnRs_00_R', u'CrnRs_01_R', u'CrnRs_02_R', u'CrnRs_03_R', u'CrnRs_04_R', u'CrnShrp_00_L', u'CrnShrp_00_R', u'Dmpl_00_L', u'Dmpl_01_L', u'Dmpl_02_L', u'Dmpl_03_L', u'Dmpl_00_R', u'Dmpl_01_R', u'Dmpl_02_R', u'Dmpl_03_R', u'Fnl_00_L', u'Fnl_01_L', u'Fnl_02_L', u'Fnl_03_L', u'Fnl_04_L', u'Fnl_05_L', u'Fnl_06_L', u'Fnl_07_L', u'Fnl_00_R', u'Fnl_01_R', u'Fnl_02_R', u'Fnl_03_R', u'Fnl_04_R', u'Fnl_05_R', u'Fnl_06_R', u'Fnl_07_R', u'JwDrp_00_L', u'JwDrp_00_R', u'JwOpnLk_00_L', u'JwOpnLk_00_R', u'JwOpn_00_L', u'JwOpn_00_R', u'LKR_00_L', u'LKR_01_L', u'LKR_02_L', u'LKR_03_L', u'LKR_04_L', u'LKR_05_L', u'LKR_06_L', u'LKR_07_L', u'LKR_08_L', u'LKR_00_R', u'LKR_01_R', u'LKR_02_R', u'LKR_03_R', u'LKR_04_R', u'LKR_05_R', u'LKR_06_R', u'LKR_07_R', u'LKR_08_R', u'LdTight_00_L', u'LdTight_01_L', u'LdTight_02_L', u'LdTight_03_L', u'LdTight_04_L', u'LdTight_05_L', u'LdTight_06_L', u'LdTight_00_R', u'LdTight_01_R', u'LdTight_02_R', u'LdTight_03_R', u'LdTight_04_R', u'LdTight_05_R', u'LdTight_06_R', u'LkDn_00_L', u'LkDn_01_L', u'LkDn_02_L', u'LkDn_03_L', u'LkDn_04_L', u'LkDn_05_L', u'LkDn_06_L', u'LkDn_07_L', u'LkDn_08_L', u'LkDn_09_L', u'LkDn_00_R', u'LkDn_01_R', u'LkDn_02_R', u'LkDn_03_R', u'LkDn_04_R', u'LkDn_05_R', u'LkDn_06_R', u'LkDn_07_R', u'LkDn_08_R', u'LkDn_09_R', u'LkL_00_L', u'LkL_01_L', u'LkL_02_L', u'LkL_03_L', u'LkL_04_L', u'LkL_05_L', u'LkL_06_L', u'LkL_07_L', u'LkL_08_L', u'LkL_00_R', u'LkL_01_R', u'LkL_02_R', u'LkL_03_R', u'LkL_04_R', u'LkL_05_R', u'LkL_06_R', u'LkL_07_R', u'LkL_08_R', u'LkUp_00_L', u'LkUp_01_L', u'LkUp_02_L', u'LkUp_03_L', u'LkUp_04_L', u'LkUp_05_L', u'LkUp_06_L', u'LkUp_07_L', u'LkUp_08_L', u'LkUp_09_L', u'LkUp_00_R', u'LkUp_01_R', u'LkUp_02_R', u'LkUp_03_R', u'LkUp_04_R', u'LkUp_05_R', u'LkUp_06_R', u'LkUp_07_R', u'LkUp_08_R', u'LkUp_09_R', u'LpFat_00_L', u'LpFat_01_L', u'LpFat_02_L', u'LpFat_03_L', u'LpFat_04_L', u'LpFat_00_R', u'LpFat_01_R', u'LpFat_02_R', u'LpFat_03_R', u'LpFat_04_R', u'LpInFat_00_L', u'LpInFat_01_L', u'LpInFat_00_R', u'LpInFat_01_R', u'LpRolIn_00_L', u'LpRolIn_01_L', u'LpRolIn_02_L', u'LpRolIn_03_L', u'LpRolIn_04_L', u'LpRolIn_05_L', u'LpRolIn_06_L', u'LpRolIn_07_L', u'LpRolIn_00_R', u'LpRolIn_01_R', u'LpRolIn_02_R', u'LpRolIn_03_R', u'LpRolIn_04_R', u'LpRolIn_05_R', u'LpRolIn_06_R', u'LpRolIn_07_R', u'LpThin_00_L', u'LpThin_01_L', u'LpThin_02_L', u'LpThin_00_R', u'LpThin_01_R', u'LpThin_02_R', u'LwrLpDprs_00_L', u'LwrLpDprs_01_L', u'LwrLpDprs_02_L', u'LwrLpDprs_03_L', u'LwrLpDprs_04_L', u'LwrLpDprs_00_R', u'LwrLpDprs_01_R', u'LwrLpDprs_02_R', u'LwrLpDprs_03_R', u'LwrLpDprs_04_R', u'LwrLpRol_00_L', u'LwrLpRol_00_R', u'MouthFrw_00_L', u'MouthFrw_01_L', u'MouthFrw_00_R', u'MouthFrw_01_R', u'MouthL_00_L', u'MouthL_01_L', u'MouthL_02_L', u'MouthL_03_L', u'MouthL_04_L', u'MouthL_05_L', u'MouthL_06_L', u'MouthL_07_L', u'MouthL_08_L', u'MouthL_00_R', u'MouthL_01_R', u'MouthL_02_R', u'MouthL_03_R', u'MouthL_04_R', u'MouthL_05_R', u'MouthL_06_R', u'MouthL_07_R', u'MouthL_08_R', u'MouthPrs_00_L', u'MouthPrs_00_R', u'MouthR_00_L', u'MouthR_01_L', u'MouthR_02_L', u'MouthR_03_L', u'MouthR_04_L', u'MouthR_05_L', u'MouthR_06_L', u'MouthR_07_L', u'MouthR_08_L', u'MouthR_00_R', u'MouthR_01_R', u'MouthR_02_R', u'MouthR_03_R', u'MouthR_04_R', u'MouthR_05_R', u'MouthR_06_R', u'MouthR_07_R', u'MouthR_08_R', u'MouthTt_00_L', u'MouthTt_01_L', u'MouthTt_02_L', u'MouthTt_03_L', u'MouthTt_04_L', u'MouthTt_05_L', u'MouthTt_06_L', u'MouthTt_07_L', u'MouthTt_08_L', u'MouthTt_00_R', u'MouthTt_01_R', u'MouthTt_02_R', u'MouthTt_03_R', u'MouthTt_04_R', u'MouthTt_05_R', u'MouthTt_06_R', u'MouthTt_07_R', u'MouthTt_08_R', u'NlDp_00_L', u'NlDp_01_L', u'NlDp_02_L', u'NlDp_00_R', u'NlDp_01_R', u'NlDp_02_R', u'NosL_00_L', u'NosL_00_R', u'NosR_00_L', u'NosR_00_R', u'NosWrnkl_00_L', u'NosWrnkl_01_L', u'NosWrnkl_02_L', u'NosWrnkl_03_L', u'NosWrnkl_04_L', u'NosWrnkl_05_L', u'NosWrnkl_06_L', u'NosWrnkl_00_R', u'NosWrnkl_01_R', u'NosWrnkl_02_R', u'NosWrnkl_03_R', u'NosWrnkl_04_R', u'NosWrnkl_05_R', u'NosWrnkl_06_R', u'NosDn_00_L', u'NosDn_00_R', u'NosUp_00_L', u'NosUp_00_R', u'Pkr_00_L', u'Pkr_01_L', u'Pkr_02_L', u'Pkr_03_L', u'Pkr_04_L', u'Pkr_05_L', u'Pkr_06_L', u'Pkr_07_L', u'Pkr_00_R', u'Pkr_01_R', u'Pkr_02_R', u'Pkr_03_R', u'Pkr_04_R', u'Pkr_05_R', u'Pkr_06_R', u'Pkr_07_R', u'Sqnt_00_L', u'Sqnt_01_L', u'Sqnt_02_L', u'Sqnt_03_L', u'Sqnt_04_L', u'Sqnt_05_L', u'Sqnt_06_L', u'Sqnt_07_L', u'Sqnt_00_R', u'Sqnt_01_R', u'Sqnt_02_R', u'Sqnt_03_R', u'Sqnt_04_R', u'Sqnt_05_R', u'Sqnt_06_R', u'Sqnt_07_R', u'Strtch_00_L', u'Strtch_01_L', u'Strtch_02_L', u'Strtch_03_L', u'Strtch_04_L', u'Strtch_05_L', u'Strtch_06_L', u'Strtch_07_L', u'Strtch_08_L', u'Strtch_09_L', u'Strtch_10_L', u'Strtch_00_R', u'Strtch_01_R', u'Strtch_02_R', u'Strtch_03_R', u'Strtch_04_R', u'Strtch_05_R', u'Strtch_06_R', u'Strtch_07_R', u'Strtch_08_R', u'Strtch_09_R', u'Strtch_10_R', u'UprLdRs_00_L', u'UprLdRs_01_L', u'UprLdRs_02_L', u'UprLdRs_03_L', u'UprLdRs_04_L', u'UprLdRs_05_L', u'UprLdRs_00_R', u'UprLdRs_01_R', u'UprLdRs_02_R', u'UprLdRs_03_R', u'UprLdRs_04_R', u'UprLdRs_05_R', u'UprLdDn_00_L', u'UprLdDn_01_L', u'UprLdDn_02_L', u'UprLdDn_03_L', u'UprLdDn_04_L', u'UprLdDn_05_L', u'UprLdDn_00_R', u'UprLdDn_01_R', u'UprLdDn_02_R', u'UprLdDn_03_R', u'UprLdDn_04_R', u'UprLdDn_05_R', u'UprLpDprs_00_L', u'UprLpDprs_01_L', u'UprLpDprs_00_R', u'UprLpDprs_01_R', u'UprLpRs_00_L', u'UprLpRs_01_L', u'UprLpRs_02_L', u'UprLpRs_03_L', u'UprLpRs_04_L', u'UprLpRs_05_L', u'UprLpRs_06_L', u'UprLpRs_00_R', u'UprLpRs_01_R', u'UprLpRs_02_R', u'UprLpRs_03_R', u'UprLpRs_04_R', u'UprLpRs_05_R', u'UprLpRs_06_R', u'Blnk_L', u'Blnk_R', u'BrInDn_BrLr_L', u'BrInDn_BrLr_R', u'BrInRs_BrInDn_L', u'BrInRs_BrInDn_R', u'BrInRs_BrLr_L', u'BrInRs_BrLr_R', u'BrInRs_UprldDn_L', u'BrInRs_UprldDn_R', u'BrLr_LidTt_L', u'BrLr_LidTt_R', u'BrLr_UpLdDn_LdT_L', u'BrLr_UpLdDn_LdT_R', u'BrLr_UprldDn_L', u'BrLr_UprldDn_R', u'BrOutRs_UprldDn_L', u'BrOutRs_UprldDn_R', u'ChkBlw_B_L', u'ChkBlw_B_R', u'ChkBlw_T_L', u'ChkBlw_T_R', u'CrnPl_JwOpn_L', u'CrnPl_JwOpn_R', u'CrnPl_LwrLpDprs_L', u'CrnPl_LwrLpDprs_R', u'EyeSqz_L', u'EyeSqz_R', u'Fnl_Cls_L', u'Fnl_Cls_R', u'JwRLk_L', u'JwRLk_R', u'JwBkLk_L', u'JwBkLk_R', u'JwClnch_L', u'JwClnch_R', u'JwFrwLk_L', u'JwFrwLk_R', u'JwLLk_L', u'JwLLk_R', u'LdT_ChkRs_L', u'LdT_ChkRs_R', u'LdT_UprLdDn_L', u'LdT_UprLdDn_R', u'LkDnPrg_L', u'LkDnPrg_R', u'LpBlw_B_L', u'LpBlw_B_R', u'LpBlw_T_L', u'LpBlw_T_R', u'LwrLdDn_L', u'LwrLdDn_R', u'LwrLdRs_L', u'LwrLdRs_R', u'LwrLpBk_L', u'LwrLpBk_R', u'NekBlw_L', u'NekBlw_R', u'NekMscle_L', u'NekMscle_R', u'NekSlide_L', u'NekSlide_R', u'NekTns_JwOpn_L', u'NekTns_JwOpn_R', u'NekTns_L', u'NekTns_R', u'NosCls_L', u'NosCls_R', u'NosOpn_L', u'NosOpn_R', u'Sqnt_UprLdDn_L', u'Sqnt_UprLdDn_R', u'StickyLips1_L', u'StickyLips1_R', u'StickyLips2_L', u'StickyLips2_R', u'StickyLips3_L', u'StickyLips3_R', u'StickyLips4_L', u'StickyLips4_R', u'StickyLips5_L', u'StickyLips5_R', u'Strtch_Cls_L', u'Strtch_Cls_R', u'Strtch_CrnPl_L', u'Strtch_CrnPl_R', u'Strtch_JwOpn_L', u'Strtch_JwOpn_R', u'Suck_L', u'Suck_R', u'Tight_L', u'Tight_R', u'UprLdDrp_L', u'UprLdDrp_R', u'UprLpBk_L', u'UprLpBk_R', u'UprLpRol_L', u'UprLpRol_R', u'UprLpRs_ChnRs_L', u'UprLpRs_ChnRs_R', u'UprLpRs_Cls_L', u'UprLpRs_Cls_R', u'Wide_L', u'Wide_R', u'UprLdDn_ChkRs_L', u'UprLdDn_ChkRs_R', u'ChnRs_Flat_TL', u'ChnRs_Flat_BL', u'ChnRs_Flat_TR', u'ChnRs_Flat_BR', u'Fnl_Prg_TL', u'Fnl_Prg_BL', u'Fnl_Prg_TR', u'Fnl_Prg_BR', u'LpBit_TL', u'LpBit_BL', u'LpBit_TR', u'LpBit_BR', u'LpRolIn_ChnRs_TL', u'LpRolIn_ChnRs_BL', u'LpRolIn_ChnRs_TR', u'LpRolIn_ChnRs_BR', u'LpRolIn_JwOpn_TL', u'LpRolIn_JwOpn_BL', u'LpRolIn_JwOpn_TR', u'LpRolIn_JwOpn_BR', u'LpRolIn_Prg_TL', u'LpRolIn_Prg_BL', u'LpRolIn_Prg_TR', u'LpRolIn_Prg_BR', u'Mouth_Prs_Tt_TL', u'Mouth_Prs_Tt_BL', u'Mouth_Prs_Tt_TR', u'Mouth_Prs_Tt_BR', u'MouthTt_Pkr_TL', u'MouthTt_Pkr_BL', u'MouthTt_Pkr_TR', u'MouthTt_Pkr_BR', u'Pkr_Fnl_TL', u'Pkr_Fnl_BL', u'Pkr_Fnl_TR', u'Pkr_Fnl_BR', u'MouthFrw_Fnl_TL', u'MouthFrw_Fnl_BL', u'MouthFrw_Fnl_TR', u'MouthFrw_Fnl_BR']

# 자동 컨스트레인을 위해서 Sam의 눈과 눈썹쪽 버텍스 리스트
Constrain_Vertices = ['newMesh.vtx[1278:1280]', 'newMesh.vtx[1286:1287]', 'newMesh.vtx[1370:1372]',
                      'newMesh.vtx[1378]', 'newMesh.vtx[1380]', 'newMesh.vtx[1643:1644]',
                      'newMesh.vtx[1660:1661]', 'newMesh.vtx[1668:1669]', 'newMesh.vtx[1672]',
                      'newMesh.vtx[1677]', 'newMesh.vtx[1681]', 'newMesh.vtx[1705]', 'newMesh.vtx[1749:1750]',
                      'newMesh.vtx[1753]', 'newMesh.vtx[1759]', 'newMesh.vtx[1779:1780]', 'newMesh.vtx[1783]',
                      'newMesh.vtx[1787]', 'newMesh.vtx[1794]', 'newMesh.vtx[1797]', 'newMesh.vtx[1808:1809]',
                      'newMesh.vtx[1814]', 'newMesh.vtx[1854:1855]', 'newMesh.vtx[2709:2711]',
                      'newMesh.vtx[2713]', 'newMesh.vtx[2806:2807]', 'newMesh.vtx[2811]',
                      'newMesh.vtx[4709:4711]', 'newMesh.vtx[4716]', 'newMesh.vtx[4718]',
                      'newMesh.vtx[4801:4803]', 'newMesh.vtx[4809]', 'newMesh.vtx[4811]',
                      'newMesh.vtx[5067:5068]', 'newMesh.vtx[5085:5086]', 'newMesh.vtx[5093]',
                      'newMesh.vtx[5095]', 'newMesh.vtx[5097]', 'newMesh.vtx[5102]', 'newMesh.vtx[5105]',
                      'newMesh.vtx[5130]', 'newMesh.vtx[5174]', 'newMesh.vtx[5176]', 'newMesh.vtx[5178]',
                      'newMesh.vtx[5184]', 'newMesh.vtx[5204:5205]', 'newMesh.vtx[5208]', 'newMesh.vtx[5212]',
                      'newMesh.vtx[5220]', 'newMesh.vtx[5222]', 'newMesh.vtx[5233]', 'newMesh.vtx[5235]',
                      'newMesh.vtx[5239]', 'newMesh.vtx[5279:5280]', 'newMesh.vtx[6082:6083]',
                      'newMesh.vtx[6085]', 'newMesh.vtx[6087]', 'newMesh.vtx[6179:6180]', 'newMesh.vtx[6184]',
                      'newMesh.vtx[168]', 'newMesh.vtx[174]', 'newMesh.vtx[3086:3087]', 'newMesh.vtx[3089]',
                      'newMesh.vtx[3106:3107]', 'newMesh.vtx[3109]', 'newMesh.vtx[3229]',
                      'newMesh.vtx[3241:3242]', 'newMesh.vtx[3247]', 'newMesh.vtx[3250]', 'newMesh.vtx[3266]',
                      'newMesh.vtx[3578]', 'newMesh.vtx[3580]', 'newMesh.vtx[3607]', 'newMesh.vtx[3609]',
                      'newMesh.vtx[3614]', 'newMesh.vtx[6450:6452]', 'newMesh.vtx[6470:6471]',
                      'newMesh.vtx[6473]', 'newMesh.vtx[6591]', 'newMesh.vtx[6603:6604]', 'newMesh.vtx[6609]',
                      'newMesh.vtx[6612]', 'newMesh.vtx[6629]']

IdentityAll = ['identity000', 'identity001', 'identity002', 'identity003', 'identity004', 'identity005', 'identity006', 'identity007', 'identity008', 'identity009', 'identity010', 'identity011', 'identity012', 'identity013', 'identity014', 'identity015', 'identity016', 'identity017', 'identity018', 'identity019', 'identity020', 'identity021', 'identity022', 'identity023', 'identity024', 'identity025', 'identity026', 'identity027', 'identity028', 'identity029', 'identity030', 'identity031', 'identity032', 'identity033', 'identity034', 'identity035', 'identity036', 'identity037', 'identity038', 'identity039', 'identity040', 'identity041', 'identity042', 'identity043', 'identity044', 'identity045', 'identity046', 'identity047', 'identity048', 'identity049', 'identity050', 'identity051', 'identity052', 'identity053', 'identity054', 'identity055', 'identity056', 'identity057', 'identity058', 'identity059', 'identity060', 'identity061', 'identity062', 'identity063', 'identity064', 'identity065', 'identity066', 'identity067', 'identity068', 'identity069', 'identity070', 'identity071', 'identity072', 'identity073', 'identity074', 'identity075', 'identity076', 'identity077', 'identity078', 'identity079', 'identity080', 'identity081', 'identity082', 'identity083', 'identity084', 'identity085', 'identity086', 'identity087', 'identity088', 'identity089', 'identity090', 'identity091', 'identity092', 'identity093', 'identity094', 'identity095', 'identity096', 'identity097', 'identity098', 'identity099']
Identity10 = ['identity000', 'identity001', 'identity002', 'identity003', 'identity004', 'identity005', 'identity006', 'identity007', 'identity008', 'identity009', 'identity010']
Identity20 = ['identity011', 'identity012', 'identity013', 'identity014', 'identity015', 'identity016', 'identity017', 'identity018', 'identity019', 'identity020']
Identity30 = ['identity021', 'identity022', 'identity023', 'identity024', 'identity025', 'identity026', 'identity027', 'identity028', 'identity029', 'identity030']
Identity40 = ['identity031', 'identity032', 'identity033', 'identity034', 'identity035', 'identity036', 'identity037', 'identity038', 'identity039', 'identity040']
Identity50 = ['identity041', 'identity042', 'identity043', 'identity044', 'identity045', 'identity046', 'identity047', 'identity048', 'identity049', 'identity050']
Identity60 = ['identity051', 'identity052', 'identity053', 'identity054', 'identity055', 'identity056', 'identity057', 'identity058', 'identity059', 'identity060']
Identity70 = ['identity061', 'identity062', 'identity063', 'identity064', 'identity065', 'identity066', 'identity067', 'identity068', 'identity069', 'identity070']
Identity80 = ['identity071', 'identity072', 'identity073', 'identity074', 'identity075', 'identity076', 'identity077', 'identity078', 'identity079', 'identity080']
Identity90 = ['identity081', 'identity082', 'identity083', 'identity084', 'identity085', 'identity086', 'identity087', 'identity088', 'identity089', 'identity090']
Identity99 = ['identity091', 'identity092', 'identity093', 'identity094', 'identity095', 'identity096', 'identity097', 'identity098', 'identity099']